<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
<?php echo $this->formUploadTemplate;
?>
<script type="text/javascript">
jQuery('#uploadImageSubmit').one('click', function (evt) {

    evt.preventDefault();
     jQuery(this).closest('form').ajaxForm({
     complete:function(xhr){
        //alert(xhr.responseText);
        jQuery('#dialogDiv').html(xhr.responseText);
        evt.preventDefault();
        },
     success: function(data){
     //alert('s');
     //AJAX FORM GIVES ALWAYS ERROR, SO PUT EVERYTHING onComplete
//alert(data) ;        
        //evt.preventDefault();
        //return false;       
     }     
     });     
    });
</script>
