<?php
/**
* CMS-IDE Visual CMS
*
* @category   Layouts
* @package    CMS-IDE
*  Copyright (C) 2010-2021  Nebojsa Tomic
*
*  This file is part of CMS-IDE.
*
*  CMS-IDE is free software; you can redistribute it and/or
*  modify it under the terms of the GNU Lesser General Public
*  License as published by the Free Software Foundation; either
*  version 3 of the License, or (at your option) any later version.
*
*  CMS-IDE is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
*  Lesser General Public License for more details.
*
*  You should have received a copy of the GNU Lesser General Public
*  License along with this library; if not, write to the Free Software
*  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
*
*/
?>
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="generator" content="NeT">
  <title>Creator Login</title>
  <link rel="shortcut icon" type="image/x-icon" href="/images/ide21logo.svg" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
<!--<link href="/daisy/daisyui.full.min.css" rel="stylesheet" type="text/css" />-->
<link href="/css/tailwind.output.css" rel="stylesheet" type="text/css" />
<script src="/daisy/daisyui.tailwind.3.4.3.js"></script>
  
</head>
<body >
  <div class="grid grid-cols-1 place-items-center h-screen">
    
    <div class="place-self-strech self-center bg-secondary p-10 md:m-10 min-w-64 rounded-box text-primary-content drop-shadow-xl" data-theme="nord">
      
      <div class="grid place-items-center place-self-strech mb-10 self-end min-w-64">
        <div class="size-24">
          <img src="/images/ide21logo.svg" height="100%" />
        </div>
      </div><!-- logo container -->

      <div class="dropdown self-center w-full">
        <div tabindex="0" role="button" class="btn btn-sm w-full">
          Theme
          <svg width="12px" height="12px" class="h-2 w-2 fill-current opacity-60 inline-block" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2048 2048"><path d="M1799 349l242 241-1017 1017L7 590l242-241 775 775 775-775z"></path></svg>
        </div>
        <ul tabindex="0" class="dropdown-content z-[1] p-2 shadow-2xl bg-base-300 rounded-box w-full">
          <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start" aria-label="System" value="default"/></li>
          <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start" aria-label="Nord" value="nord"/></li>
          <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start" aria-label="Retro" value="retro"/></li>
        </ul>
      </div>
      <?php
      echo $this->form;
      ?>
    </div><!-- form container -->
  </div><!-- main container-->
</body>
</html>