<?php
/**
* IDE21 Content Management System
*
* @category   Layouts
* @package    IDE21
*  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
*
*  This file is part of IDE21.
*
*  IDE21 is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
*
*
*
*/
?>
<!DOCTYPE html>
<html class="min-h-dvh h-full" data-theme="nord">
<head>
  <meta name="keywords" content="<?php echo $this->meta_keywords;?>" />
  <meta name="description" content="<?php echo $this->meta_description;?>" />
  <meta name="generator" content="NeT" />
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Accept-Encoding" content="gzip, deflate" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $this->title;?></title>
  <!--themes for the objects-->
  <!-- <link type="text/css" href="/css/combinedAll.css" rel="stylesheet" /> -->
  <!--<link type="text/css" href="/css/themes.css" rel="stylesheet" />-->
  <link rel="stylesheet" href="/css/default.css?rnd=<?php echo rand();?>"  /><!--CSS written in admin panel-->
  <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
  <?php echo $this->headLink(); ?>
  <?php
  if($this->staticFilesCSS != '') {
    foreach($this->staticFilesCSS as $cssFile){
      ?>
      <link type="text/css" href="<?php echo $cssFile;?>" rel="stylesheet" />
      <?php
    }
  }
  ?>
  <link href="/css/tailwind.output.css" rel="stylesheet" type="text/css" />
  <script src="/daisy/daisyui.tailwind.3.4.3.js"></script>

  <script type="text/javascript" >
  absoluteUrl = "<?php echo $this->host;?>";
  templateId =  "<?php echo $this->template;?>";
  </script>

  <script type="text/javascript" src="/js/jquery/jquery-1.3.2.min.js"></script>
  <!--<script type="text/javascript" src="/js/combinedAll.js" ></script>-->


  <!-- <script type="text/javascript" src="/js/js/easySlider1.5.js"></script> -->
  <!-- <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.5.3/jquery-ui.min.js" ></script> -->

</head>
<body style="background:<?php echo $this->templateBodyBackground;?>;" class="overflow-x-hidden w-full min-h-dvh h-auto bg-cover">
  <div class="top"></div>
  <div id ="container" class="">
    <div id="centerWrapper" class="wrapper">
      <div id="content">
        <?php
        echo $this->layout()->content;
        //echo $this->layout()->ajaxContent ;
        ?>
      </div>
    </div>
  </div>
  <?php
  if(!empty($this->staticFilesJS) ){
    foreach($this->staticFilesJS as $jsFile){
      ?>
      <!--<script type="text/javascript" src="<?php echo $jsFile;?>"></script>-->
      <?php
    }
  } else {
    ?>
    <!--<script type="text/javascript" src="/js/main2.js?rnd=<?php echo rand();?>"></script>-->
    <?php
  }
  ?>
  <script type="text/javascript">
    $('select').addClass('select-sm shadow-sm');
    $('input').addClass('input input-sm w-full shadow-sm');
    $('input[type="submit"]').addClass('btn btn-secondary shadow-lg');

  </script>
</body>
</html>
