<?php
/**
* CMS-IDE Visual CMS
*
* @category   Layouts
* @package    CMS-IDE
*  Copyright (C) 2010-2021  Nebojsa Tomic
*
*  This file is part of CMS-IDE.
*
*  CMS-IDE is free software; you can redistribute it and/or
*  modify it under the terms of the GNU Lesser General Public
*  License as published by the Free Software Foundation; either
*  version 3 of the License, or (at your option) any later version.
*
*  CMS-IDE is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
*  Lesser General Public License for more details.
*
*  You should have received a copy of the GNU Lesser General Public
*  License along with this library; if not, write to the Free Software
*  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
*
*/
?>
<?php require("css_browser_selector.php"); ?>
<!DOCTYPE html>
<html lang="en" class="<?php echo css_browser_selector() ?> overflow-hidden">
<head>
  <meta name="keywords" content="<?php echo $this->meta_description;?>" />
  <meta name="description" content="<?php echo $this->meta_description;?>" />
  <meta name="generator" content="NeT" />
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $this->title;?> - <?php echo $this->version;?> </title>
  <link rel="stylesheet" href="/css/creator/creator.css" type="text/css" />
  <link rel="stylesheet" href="/css/jdMenu/blue/jquery.jdMenu.css" type="text/css" />
  <link rel="stylesheet" href="/css/default.css" type="text/css" /><!--CSS written in admin panel-->
  <link rel="stylesheet" href="/css/backend.css" type="text/css" /><!--CSS written for the admin panel-->
  <!--TABLE GRID STYLES
  <link rel="stylesheet" type="text/css" media="screen" href="/js/jqgrid/themes/redmond/jquery-ui-1.7.1.custom.css" />
  <link rel="stylesheet" type="text/css" media="screen" href="/js/jqgrid/themes/ui.jqgrid.css" />-->
  <!--treeView-->
  <link rel="stylesheet" href="/css/treeView/jquery.treeview.css" type="text/css" />
  <link rel="stylesheet" href="/css/treeView/screen.css" type="text/css" />
  <!--lightBox-->
  <link rel="stylesheet" href="/css/lightbox/jquery.lightbox-0.5.css" type="text/css" />
  <link rel="stylesheet" href="/css/lightbox/thickbox.css" type="text/css" media="screen" />
  <!--color picker-->
  <link rel="stylesheet" media="screen" type="text/css" href="/css/colorpicker.css" />
  <link rel="stylesheet" href="/css/default.css" type="text/css" /><!--CSS written in admin panel-->
  <link rel="stylesheet" href="/css/backend.css" type="text/css" /><!--CSS written for the admin panel-->
  <link type="text/css" href="/css/jqUI/ui.all.css" rel="stylesheet" />
  <link type="text/css" href="/css/defaultWidgets.css" rel="stylesheet" />
  <!--themes for the objects-->
  <link type="text/css" href="/css/themes.css" rel="stylesheet" />
  <link rel="shortcut icon" type="image/x-icon" href="/images/ide21logo.svg">
  <link rel="stylesheet" href="/css/uniform/css/uniform.aristo.css" media="screen" />
  <!-- Add fancyBox
  <link rel="stylesheet" href="<?php echo $this->host;?>fancybox/2/jquery.fancybox.css" type="text/css" media="screen" />-->


  <!--<link href="/daisy/daisyui.full.min.css" rel="stylesheet" type="text/css" />-->
  <link href="/css/tailwind.output.css" rel="stylesheet" type="text/css" />
  <script src="/daisy/daisyui.tailwind.3.4.3.js"></script>

  
  <script type="text/javascript" >
  absoluteUrl = "<?php echo $this->hostRW;?>";
  absoluteUrl2 = "<?php echo $this->host;?>";
  </script>

  <script src="https://code.jquery.com/jquery-1.10.1.min.js"></script>
  <script src="https://code.jquery.com/jquery-migrate-1.2.1.js"></script>
  <!--<script type="text/javascript" src="/js/combinedAll.js"></script>-->
  <script type="text/javascript" src="/js/jquery/jquery.ui.js"></script>
  <script type="text/javascript" src="/js/jquery/jquery.livequery.js"></script>
  <script type="text/javascript" src="/js/jquery/colorpicker.js"></script>
  <script type="text/javascript" src="/js/jquery/ui.draggable.js"></script>
  <script type="text/javascript" src="/js/jquery/ui.droppable.js"></script>
  <script type="text/javascript" src="/js/jquery/ui.resizable.js"></script>

  <script type="text/javascript" src="/js/jquery/jquery.jdMenu.js"></script>
  <script type="text/javascript" src="/js/jquery/jquery.treeview.js"></script>
  <script type="text/javascript" src="/js/jquery/jquery.form.js"></script>

  <script type="text/javascript" src="/js/jquery/alajax.js"></script>
  <!--dialog-->
  <script type="text/javascript" src="/js/jquery/ui.dialog.js"></script>
  <script type="text/javascript" src="/js/jquery/ui.position.js"></script>

  <script type="text/javascript" src="/js/jqgrid/js/jquery.contextmenu.js" ></script>
  <script type="text/javascript" src="/js/jquery/thickbox.js"></script>
  <script language="JavaScript" type="text/javascript" src="/js/wysiwyg/tiny_mce/tiny_mce.js"></script>

  <script type="text/javascript"  src="/js/uniform/jquery.uniform.js"></script>
  <script type="text/javascript" src="/js/jqtransformplugin/jquery.jqtransform.js"></script>

  <script type="text/javascript" src="/fancybox/2/jquery.fancybox.js"></script>
  <?php echo $this->headScript(); ?>
</head>
<body class="overflow-hidden">
  <!-- top panel -->
  <div class="navbar bg-neutral min-h-12 h-12 relative" style="z-index:999999;">
    <div class="navbar-start flex gap-2 md:gap-4">
      <!--<div class="dropdown">
        <div tabindex="0" role="button" class="btn btn-sm btn-ghost btn-circle text-white">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h7" /></svg>
        </div>
        <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
          <li><a>Homepage</a></li>
          <li><a>Portfolio</a></li>
          <li><a>About</a></li>
        </ul>
      </div>-->
      <div id ="contPreview" class="hidden w-full h-auto absolute top-52 left-72 bg-white" style="z-index: 9999999;"></div><!-- z-index must be like this for now, since a lot of interaction with droppables relies on the order of elements, it should be rewritten to something more sensible, for all elements in the admin panel -->
      <div id="toggleProperties"  class="help cursor-pointer btn btn-sm btn-ghost btn-circle text-white" title="<?php echo $this->translate->_("Click to toggle properties box");?>">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
          <path d="M3.53 2.47a.75.75 0 0 0-1.06 1.06l18 18a.75.75 0 1 0 1.06-1.06l-18-18ZM22.676 12.553a11.249 11.249 0 0 1-2.631 4.31l-3.099-3.099a5.25 5.25 0 0 0-6.71-6.71L7.759 4.577a11.217 11.217 0 0 1 4.242-.827c4.97 0 9.185 3.223 10.675 7.69.12.362.12.752 0 1.113Z" />
          <path d="M15.75 12c0 .18-.013.357-.037.53l-4.244-4.243A3.75 3.75 0 0 1 15.75 12ZM12.53 15.713l-4.243-4.244a3.75 3.75 0 0 0 4.244 4.243Z" />
          <path d="M6.75 12c0-.619.107-1.213.304-1.764l-3.1-3.1a11.25 11.25 0 0 0-2.63 4.31c-.12.362-.12.752 0 1.114 1.489 4.467 5.704 7.69 10.675 7.69 1.5 0 2.933-.294 4.242-.827l-2.477-2.477A5.25 5.25 0 0 1 6.75 12Z" />
        </svg>

      </div>

      <div id="newItem" class="help cursor-pointer btn btn-sm btn-ghost btn-circle text-white" title="<?php echo $this->translate->_("Click to create new object on this page");?>">
        <svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
          <path fill-rule="evenodd" d="M5.625 1.5H9a3.75 3.75 0 0 1 3.75 3.75v1.875c0 1.036.84 1.875 1.875 1.875H16.5a3.75 3.75 0 0 1 3.75 3.75v7.875c0 1.035-.84 1.875-1.875 1.875H5.625a1.875 1.875 0 0 1-1.875-1.875V3.375c0-1.036.84-1.875 1.875-1.875ZM12.75 12a.75.75 0 0 0-1.5 0v2.25H9a.75.75 0 0 0 0 1.5h2.25V18a.75.75 0 0 0 1.5 0v-2.25H15a.75.75 0 0 0 0-1.5h-2.25V12Z" clip-rule="evenodd" />
          <path d="M14.25 5.25a5.23 5.23 0 0 0-1.279-3.434 9.768 9.768 0 0 1 6.963 6.963A5.23 5.23 0 0 0 16.5 7.5h-1.875a.375.375 0 0 1-.375-.375V5.25Z" />
        </svg>
      </div>
      <div id="cloneItem" class="help cursor-pointer btn btn-sm btn-ghost btn-circle text-white" title="<?php echo $this->translate->_("Click to create clone object");?>">
        <svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
          <path fill-rule="evenodd" d="M17.663 3.118c.225.015.45.032.673.05C19.876 3.298 21 4.604 21 6.109v9.642a3 3 0 0 1-3 3V16.5c0-5.922-4.576-10.775-10.384-11.217.324-1.132 1.3-2.01 2.548-2.114.224-.019.448-.036.673-.051A3 3 0 0 1 13.5 1.5H15a3 3 0 0 1 2.663 1.618ZM12 4.5A1.5 1.5 0 0 1 13.5 3H15a1.5 1.5 0 0 1 1.5 1.5H12Z" clip-rule="evenodd" />
          <path d="M3 8.625c0-1.036.84-1.875 1.875-1.875h.375A3.75 3.75 0 0 1 9 10.5v1.875c0 1.036.84 1.875 1.875 1.875h1.875A3.75 3.75 0 0 1 16.5 18v2.625c0 1.035-.84 1.875-1.875 1.875h-9.75A1.875 1.875 0 0 1 3 20.625v-12Z" />
          <path d="M10.5 10.5a5.23 5.23 0 0 0-1.279-3.434 9.768 9.768 0 0 1 6.963 6.963 5.23 5.23 0 0 0-3.434-1.279h-1.875a.375.375 0 0 1-.375-.375V10.5Z" />
        </svg>
      </div>

      <!--<div id="helpButton" class="help hidden btn btn-sm btn-ghost btn-circle text-white" title="<?php echo $this->translate->_("Click to toggle help");?>"></div>
      <div id="helpDiv"  title=""><?php echo $this->translate->_("NeT.Creator Help");?></div>-->

      <div id="delButton" class="help cursor-pointer btn btn-sm btn-ghost btn-circle text-white" title="<?php echo $this->translate->_("Click to delete selected object");?>">
        <svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" >
          <path fill-rule="evenodd" d="M5.625 1.5H9a3.75 3.75 0 0 1 3.75 3.75v1.875c0 1.036.84 1.875 1.875 1.875H16.5a3.75 3.75 0 0 1 3.75 3.75v7.875c0 1.035-.84 1.875-1.875 1.875H5.625a1.875 1.875 0 0 1-1.875-1.875V3.375c0-1.036.84-1.875 1.875-1.875ZM9.75 14.25a.75.75 0 0 0 0 1.5H15a.75.75 0 0 0 0-1.5H9.75Z" clip-rule="evenodd" />
          <path d="M14.25 5.25a5.23 5.23 0 0 0-1.279-3.434 9.768 9.768 0 0 1 6.963 6.963A5.23 5.23 0 0 0 16.5 7.5h-1.875a.375.375 0 0 1-.375-.375V5.25Z" />
        </svg>
      </div>

      <div id="updateContentButton" class="help cursor-pointer btn btn-sm btn-ghost btn-circle text-white" title="<?php echo $this->translate->_("Click this to update the content of the selected object") . " after editing in tinyMCE.";?>"> <a id="tinySave" href=""  class="navLinks a_refresh noAjaxEvent help" title="<?php echo $this->translate->_("Click this to update the content of the selected object");?>">
        <svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
          <path fill-rule="evenodd" d="M4.755 10.059a7.5 7.5 0 0 1 12.548-3.364l1.903 1.903h-3.183a.75.75 0 1 0 0 1.5h4.992a.75.75 0 0 0 .75-.75V4.356a.75.75 0 0 0-1.5 0v3.18l-1.9-1.9A9 9 0 0 0 3.306 9.67a.75.75 0 1 0 1.45.388Zm15.408 3.352a.75.75 0 0 0-.919.53 7.5 7.5 0 0 1-12.548 3.364l-1.902-1.903h3.183a.75.75 0 0 0 0-1.5H2.984a.75.75 0 0 0-.75.75v4.992a.75.75 0 0 0 1.5 0v-3.18l1.9 1.9a9 9 0 0 0 15.059-4.035.75.75 0 0 0-.53-.918Z" clip-rule="evenodd" />
        </svg>
      </a></div>
      
      <!-- <div id="moveProps" class="help" title="<?php echo $this->translate->_("Click to move around properties dialog");?>">
        <button id="upB"></button> <button id="downB"></button>
      </div> -->
    </div>
    <div class="navbar-center hidden md:flex w-8 ">
      <!--<img alt="IDE21 Logo" src="/images/ide21logo.svg">-->
    </div>
    <div class="navbar-end flex gap-2">
      <div class="dropdown" style="z-index:9;">
        <div tabindex="0" role="button" class="btn btn-sm min-h-8 h-8 w-8 rounded-full">
          <svg width="12px" height="12px" class="h-2 w-2 fill-current opacity-60 inline-block" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2048 2048"><path d="M1799 349l242 241-1017 1017L7 590l242-241 775 775 775-775z"></path></svg>
        </div>
        <ul tabindex="0" class="dropdown-content z-[99] p-2 shadow-2xl bg-base-300 rounded-box w-20">
          <!--<li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start" aria-label="System" value="default"/></li>-->
          <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start" aria-label="Nord" value="nord"/></li>
          <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start" aria-label="Retro" value="retro"/></li>
        </ul>
      </div>
      <div id="logout" class="help btn btn-sm btn-ghost btn-circle text-white mx-2 cursor-pointer" title="<?php echo $this->translate->_("Click to logout");?>">
        <a id="logout_a" class="a_logout" href="<?php echo $this->host;?>creator/logout" >
          <svg class="w-6 h-6 rotate-180" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
            <path fill-rule="evenodd" d="M16.5 3.75a1.5 1.5 0 0 1 1.5 1.5v13.5a1.5 1.5 0 0 1-1.5 1.5h-6a1.5 1.5 0 0 1-1.5-1.5V15a.75.75 0 0 0-1.5 0v3.75a3 3 0 0 0 3 3h6a3 3 0 0 0 3-3V5.25a3 3 0 0 0-3-3h-6a3 3 0 0 0-3 3V9A.75.75 0 1 0 9 9V5.25a1.5 1.5 0 0 1 1.5-1.5h6ZM5.78 8.47a.75.75 0 0 0-1.06 0l-3 3a.75.75 0 0 0 0 1.06l3 3a.75.75 0 0 0 1.06-1.06l-1.72-1.72H15a.75.75 0 0 0 0-1.5H4.06l1.72-1.72a.75.75 0 0 0 0-1.06Z" clip-rule="evenodd" />
          </svg>
        </a>
      </div>
    </div>
  </div>
  <!-- end top panel -->

  <div id="ajax-loader"></div>
  <div id="dialogDiv" class="bg-primary text-primary-content"></div>
  <div id ="container">
    <div id="content">
      <div id="templateMask"></div>
      <?php
      echo $this->layout()->content;
      ?>
    </div>
  </div>
  <script type="text/javascript" src="/js/codepressFix.js" ></script>
  <!--<script type="text/javascript" src="/js/codepress/codepress.js" ></script>-->
  <script type="text/javascript">
  $(document).ready(function() {
    //$('select, input, textarea').livequery(function(){$(this).uniform();});
  });
  </script>
  <script type="text/javascript">
  // send message to the new admin that it can show itself
  window.parent.postMessage('creator_logged_in', '*');

  window.addEventListener('message', function(message){
    //console.log(message.data);
    //$('#' + message.data).get(0).click();
  });
  </script>
</body>
</html>
