<?php
/**
* IDE21 Content Management System
*
* @category   Layouts
* @package    IDE21
*  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
*
*  This file is part of IDE21.
*
*  IDE21 is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
*
*
*
*/
?>
<!DOCTYPE html>
<html class="min-h-dvh h-full ease-in duration-800" data-theme="nord">
<head>
  <meta name="keywords" content="<?php echo $this->meta_keywords;?>" />
  <meta name="description" content="<?php echo $this->meta_description;?>" />
  <meta name="generator" content="NeT" />
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Accept-Encoding" content="gzip, deflate" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $this->title;?></title>
  <link rel="stylesheet" href="/css/jdMenu/blue/jquery.jdMenu.css" type="text/css" />
  <!--treeView-->
  <link rel="stylesheet" href="/css/treeView/jquery.treeview.css" type="text/css" />
  <link rel="stylesheet" href="/css/treeView/screen.css" type="text/css" />
  <link rel="stylesheet" href="/css/default.css?rnd=<?php echo rand();?>"  /><!--CSS written in admin panel-->
  <link rel="shortcut icon" type="image/x-icon" href="/images/logo/logo.png">
  <?php echo $this->headLink(); ?>
  <?php
  if($this->staticFilesCSS != '') {
    foreach($this->staticFilesCSS as $cssFile){
      ?>
      <link type="text/css" href="<?php echo $cssFile;?>" rel="stylesheet" />
      <?php
    }
  }
  ?>
  <link href="/daisy/daisyui@5.css" rel="stylesheet" type="text/css" />
  <link href="/daisy/daisyui@5.themes.css" rel="stylesheet" type="text/css" />
  <link href="/css/tailwind.output.css?rnd=<?php echo rand();?>" rel="stylesheet" type="text/css" />
  <script src="/daisy/tailwind.browser@4.js"></script>

  <script type="text/javascript" >
  absoluteUrl = "<?php echo $this->host;?>";
  templateId =  "<?php echo $this->template;?>";
  </script>

  <script type="text/javascript" src="/js/jquery/jquery-1.3.2.min.js"></script>
  <script type="text/javascript" src="/js/combinedAll.js" ></script>

</head>
<body style="background:<?php echo $this->templateBodyBackground;?>;" class="overflow-x-hidden w-full min-h-dvh h-auto bg-cover">
  <div class="top"></div>
  <div id ="container" class="">
    <div id="centerWrapper" class="wrapper">
      <div id="content">
        <?php
        echo $this->layout()->content;
        ?>
      </div>
    </div>
  </div>
  <?php
  if(!empty($this->staticFilesJS) ){
    foreach($this->staticFilesJS as $jsFile){
      ?>
      <!--<script type="text/javascript" src="<?php echo $jsFile;?>"></script>-->
      <?php
    }
  } else {
    ?>
    <script type="text/javascript" src="/js/main2.js?rnd=<?php echo rand();?>"></script>
    <?php
  }
  ?>
  <script type="text/javascript">
    /* add DaisyUI fixes */
    $('select').addClass('select-sm shadow-sm');
    $('input[type="text"], input[type="password"], input[type="email"]').each(function(){
      $(this).addClass('input input-sm w-full shadow-sm').attr('placeholder', $(this).attr('name'));
    });
    $('input[type="submit"]').addClass('btn btn-secondary shadow-lg');
    $('.treeview').treeview({
      collapsed: true,
      animated: "medium"
    });
    /* for displaying other then default color of the menu items, which was set in admin panel, we need to use this */
    function changeMenuColors(){
      $.each( $('.jd_menu'), function(k,v){
          const parentBackgroundColor = $(this).closest('.templateDiv').css('background-color');
          const parentFontColor = $(this).closest('.templateDiv').css('color');

          $(this).find('li').css('background-color', parentBackgroundColor);
          $(this).find('a.link').css('color', parentFontColor);
      });
    }
    changeMenuColors();
    $('.theme-controller').change(function(e){
      changeMenuColors();
    });
    /* animate click on hero buttons */
    $('.hero-content button').click(function(e){
      let scrollTarget = document.getElementById($(e.target).closest('a').attr('href').replace('#',''));
      scrollTarget.scrollIntoView({
        block: 'start',
        behavior: 'smooth',
        inline: 'start'
      });
      return false;
    });
  </script>
</body>
</html>
