<?php
/**
* CMS-IDE Visual CMS
*
* @category   Layouts
* @package    CMS-IDE
*  Copyright (C) 2010-2021  Nebojsa Tomic
*
*  This file is part of CMS-IDE.
*
*  CMS-IDE is free software; you can redistribute it and/or
*  modify it under the terms of the GNU Lesser General Public
*  License as published by the Free Software Foundation; either
*  version 3 of the License, or (at your option) any later version.
*
*  CMS-IDE is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
*  Lesser General Public License for more details.
*
*  You should have received a copy of the GNU Lesser General Public
*  License along with this library; if not, write to the Free Software
*  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
*
*/
?>
<?php require("css_browser_selector.php"); ?>
<!DOCTYPE html>
<html lang="en" class="<?php echo css_browser_selector() ?>" data-theme="nord">
<head>
  <meta name="keywords" content="<?php echo $this->meta_description;?>" />
  <meta name="description" content="<?php echo $this->meta_description;?>" />
  <meta name="generator" content="NeT" />
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title><?php echo $this->title;?> - <?php echo $this->version;?> </title>
  <link rel="stylesheet" href="/css/creator/creator.css" type="text/css" />
  <link rel="stylesheet" href="/css/jdMenu/blue/jquery.jdMenu.css" type="text/css" />
  <link rel="stylesheet" href="/css/default.css" type="text/css" /><!--CSS written in admin panel-->
  <link rel="stylesheet" href="/css/backend.css" type="text/css" /><!--CSS written for the admin panel-->
  <!--TABLE GRID STYLES
  <link rel="stylesheet" type="text/css" media="screen" href="/js/jqgrid/themes/redmond/jquery-ui-1.7.1.custom.css" />
  <link rel="stylesheet" type="text/css" media="screen" href="/js/jqgrid/themes/ui.jqgrid.css" />-->
  <!--treeView-->
  <link rel="stylesheet" href="/css/treeView/jquery.treeview.css" type="text/css" />
  <link rel="stylesheet" href="/css/treeView/screen.css" type="text/css" />
  <!--lightBox-->
  <link rel="stylesheet" href="/css/lightbox/jquery.lightbox-0.5.css" type="text/css" />
  <link rel="stylesheet" href="/css/lightbox/thickbox.css" type="text/css" media="screen" />
  <!--color picker-->
  <link rel="stylesheet" media="screen" type="text/css" href="/css/colorpicker.css" />
  <link rel="stylesheet" href="/css/default.css" type="text/css" /><!--CSS written in admin panel-->
  <link rel="stylesheet" href="/css/backend.css" type="text/css" /><!--CSS written for the admin panel-->
  <link type="text/css" href="/css/jqUI/ui.all.css" rel="stylesheet" />
  <link type="text/css" href="/css/defaultWidgets.css" rel="stylesheet" />
  <!--themes for the objects-->
  <link type="text/css" href="/css/themes.css" rel="stylesheet" />
  <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
  <link rel="stylesheet" href="/css/uniform/css/uniform.aristo.css" media="screen" />
  <!-- Add fancyBox
  <link rel="stylesheet" href="<?php echo $this->host;?>fancybox/2/jquery.fancybox.css" type="text/css" media="screen" />-->


  <!--<link href="/daisy/daisyui.full.min.css" rel="stylesheet" type="text/css" />-->
  <link href="/css/tailwind.output.css" rel="stylesheet" type="text/css" />
  <script src="/daisy/daisyui.tailwind.3.4.3.js"></script>

  
  <script type="text/javascript" >
  absoluteUrl = "<?php echo $this->hostRW;?>";
  absoluteUrl2 = "<?php echo $this->host;?>";
  </script>

  <script src="https://code.jquery.com/jquery-1.10.1.min.js"></script>
  <script src="https://code.jquery.com/jquery-migrate-1.2.1.js"></script>
  <!--<script type="text/javascript" src="/js/combinedAll.js"></script>-->
  <script type="text/javascript" src="/js/jquery/jquery.ui.js"></script>
  <script type="text/javascript" src="/js/jquery/jquery.livequery.js"></script>
  <script type="text/javascript" src="/js/jquery/colorpicker.js"></script>
  <script type="text/javascript" src="/js/jquery/ui.draggable.js"></script>
  <script type="text/javascript" src="/js/jquery/ui.droppable.js"></script>
  <script type="text/javascript" src="/js/jquery/ui.resizable.js"></script>

  <script type="text/javascript" src="/js/jquery/jquery.jdMenu.js"></script>
  <script type="text/javascript" src="/js/jquery/jquery.treeview.js"></script>
  <script type="text/javascript" src="/js/jquery/jquery.form.js"></script>

  <script type="text/javascript" src="/js/jquery/alajax.js"></script>
  <!--dialog-->
  <script type="text/javascript" src="/js/jquery/ui.dialog.js"></script>
  <script type="text/javascript" src="/js/jquery/ui.position.js"></script>

  <script type="text/javascript" src="/js/jqgrid/js/jquery.contextmenu.js" ></script>
  <script type="text/javascript" src="/js/jquery/thickbox.js"></script>
  <script language="JavaScript" type="text/javascript" src="/js/wysiwyg/tiny_mce/tiny_mce.js"></script>

  <script type="text/javascript"  src="/js/uniform/jquery.uniform.js"></script>
  <script type="text/javascript" src="/js/jqtransformplugin/jquery.jqtransform.js"></script>

  <script type="text/javascript" src="/fancybox/2/jquery.fancybox.js"></script>
  <?php echo $this->headScript(); ?>
</head>
<body>
  <div class="dropdown mb-72 absolute top-0 left-14">
    <div tabindex="0" role="button" class="btn m-1">
      Theme
      <svg width="12px" height="12px" class="h-2 w-2 fill-current opacity-60 inline-block" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2048 2048"><path d="M1799 349l242 241-1017 1017L7 590l242-241 775 775 775-775z"></path></svg>
    </div>
    <ul tabindex="0" class="dropdown-content z-[1] p-2 shadow-2xl bg-base-300 rounded-box w-52">
      <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start" aria-label="System" value="default"/></li>
      <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start" aria-label="Nord" value="nord"/></li>
      <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start" aria-label="Retro" value="retro"/></li>
    </ul>
  </div>
  <div id="ajax-loader"></div>
  <div id="dialogDiv" class="bg-primary text-primary-content"></div>
  <div id ="container">
    <div id="content">
      <?php
      echo $this->layout()->content;
      ?>
    </div>
  </div>
  <script type="text/javascript" src="/js/codepressFix.js" ></script>
  <script type="text/javascript" src="/js/codepress/codepress.js" ></script>
  <script type="text/javascript">
  $(document).ready(function() {
    //$('select, input, textarea').livequery(function(){$(this).uniform();});
  });
  </script>
  <script type="text/javascript">
  // send message to the new admin that it can show itself
  window.parent.postMessage('creator_logged_in', '*');

  window.addEventListener('message', function(message){
    //console.log(message.data);
    //$('#' + message.data).get(0).click();
  });
  </script>
</body>
</html>
