<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
<?php echo $this->formAddCategory;
?>
<script type="text/javascript">

$('#addCategoryForm').ajaxForm(function(data){

    mn = $('#newCategoryName').attr("value");
    $('#dialogDiv').remove();    

    jsin = eval("(" + data + ")" );
    catItemId = jsin["out"]["catItemId"] ;
    catMessage = jsin["out"]["message"] ;
            
    //TREBA DODATI VALUE DA BI SE UPDATOVAO ID UNESENE CATEG.
    $('#categoryName').append('<option value="' + catItemId + '">'  +  mn + "</option>");
    $('#categoryNameAssign').append('<option value="' + catItemId + '">'  +  mn + "</option>");

    ajaxEmitMessage(catMessage);
    setTimeout("clickMask()", 1000); //closing all      
    
});
</script>