<?php
/**
 * CMS-IDE Visual CMS
 *
 * @category   Layouts
 * @package    CMS-IDE
 *  Copyright (C) 2010-2021  Nebojsa Tomic
 *  
 *  This file is part of CMS-IDE.
 *     
 *  CMS-IDE is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 3 of the License, or (at your option) any later version.
 *
 *  CMS-IDE is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * 
 * 
 */
 ?>
<?php
//echo "heyyy";
echo $this->output;
if(count($this->hits)) {
?>
<b style="padding:0px;font-size:18px;">Search results:</b><br /><br /><br />
<div id="scroll">
<?php
        $i=1;
        //foreach ($this->hits as $hit) {
        ?>
        
        <h1>Search results</h1>
        <table  style="border:0px solid silver;width:100%;margin-bottom:10px;padding:0px;">
            <tr>
                <td>
        <?php
            //foreach ($hit->getDocument()->getFieldNames() as $field) {
            foreach ($this->hits as $field) {
                echo $field['title'] . "<br />";
                //echo '<tr><td  style="border:1px solid green;width:100px;">';
                if ($field == "url") {
                //echo "<b>$field: </b><br />";
                echo '    <b><a style="color:#555555;width:auto;" class="link" value="' . trim(substr($hit->$field,0,76)) . '">View page</a></b>  ';

                } else if ($field == "created") {
                //echo "<b>$field: </b><br />";
                //echo '    ' . date("d/m/Y", trim(substr($hit->$field,0,76))) . "  ";

                } else if ($field == "title"){
                //echo "<b>$field: </b><br />";
                //echo '<b>         ' . "\t" . strip_tags(trim(substr($hit->$field,0,76))) . "</b>   ";
                }
                 else if ($field == "teaser_text"){
                //echo "<b>$field: </b><br />";
                echo '<p>' . strip_tags(trim(substr($hit->$field,0,150))) . "</p> ";
                }
                //echo '</td></tr>';
            }
        $i++;
        ?>

                </td>
            </tr>
        </table>
        <?php //} 
        ?>
</div>
<?php
//echo($this->paginationControl($this->paginator, 'Sliding', 'paginator.phtml')); ?>

<?php
} else {
    //echo '<b>There are no matching results for your search.</b>';
}
?>

<script type="text/javascript">
$('body').livequery(function(){
    //$(this).css({background:"<?php echo str_replace(';', '', $this->templateBodyBackground);?>"});
});    
</script>