<!-- this file should be editable from admin panel for the current user -->
<style type="text/css">
  h1 {}
  h2 {}
  a {}
</style>
<div id="ide21-default-template-blue" class="grid grid-cols-12 rounded-lg relative bg-blue-400 md:p-8 md:w-4/5 mx-auto">
  <div id="hdr" class="header w-full h-auto min-h-72 max-h-96  overflow-hidden bg-blue-400 col-span-12">
    <img class="w-full max-w-full bg-contain" src="/images/backgrounds/vector_0012.png" alt="" />
  </div>
  <div class="col-span-6  inline-flex items-center gap-2 pl-8">{language:flags}</div><div class="col-span-6  grid  justify-items-end h-20">{searchform}</div>
  <div id="wrp" class="grid grid-cols-12 col-span-12">
    <div id="sdb" class="leftcolumn col-span-12 md:col-span-4 bg-blue-200 p-8">
      <div id="t1menu" >{menu:display:1:vertical}</div>
      <div>{liveblock:user:loginArea}</div>
      <div>
        <p>{adminurl}</p>
      </div>
    </div>
    <div id="cnt" class="sheet col-span-12 md:col-span-8 bg-blue-100 p-8">
      <div class=""><h1 class="text-2xl">{title}</h1></div>
      <div class="">{content}</div>
    </div>
  </div>
  <div id="ftr" class="col-span-12 bg-blue-400 p-8">
    <div>
      <p>Copyright © 2010-present Nebojsa Tomic | Powered by <a href="#" target="_blank">IDE21</a></p>
    </div>
  </div>
</div>