<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *
 *
 *
 *
 *
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 *
 *
 *
 *
 *
 * 
 * 
 */
 ?>
<?php echo $this->formAddFolder;
?>
<script type="text/javascript">

$('#addFolderForm').ajaxForm(function(data){

    mn = $('#newFolderName').attr("value");
      
    
    //alert(data + " *<?php echo $this->menuName;?>"); 
    if (mn != "") {
        $('#dialogDiv').remove();  
        $('#folderNames').append("<option>" +  mn + "</option>");
        ajaxEmitMessage(lang.FolderAdded);
        setTimeout("clickMask()", 1000); //closing all  
    } else {
        $('#ajaxEventMessage').remove();
        $('#dialogDiv').html('<div id="closeDialogDiv"></div>' + data);
    }


    
});
</script>