<?php

/**

 * IDE21 Content Management System

 *

 * @category   Layouts

 * @package    IDE21

 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)

 *  

 *  This file is part of IDE21.

 *     

 *

 *

 *

 *

 *

 *  IDE21 is distributed in the hope that it will be useful,

 *  but WITHOUT ANY WARRANTY; without even the implied warranty of

 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 *

 *

 *

 *

 *

 *

 * 

 * 

 */

 ?>

<img width="100%" height="100%" src="<?php echo $this->host;?>images/<?php echo $this->imageDetailFolder;?>/<?php echo $this->imageDetail;?>" />