<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
<div class="breadcrumbs blackTheme">
<?php
//print_r($this->paths);
//echo $this->host;
foreach ($this->paths as $path){
?>
<a href="<?php  echo $this->host . $path['url'];?>">  <?php echo $path['url'];?> </a>&nbsp;>
<?php
}
?>
</div>