<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
<?php
//print_r($this->category);
//print_r($this->categoryName);
$host = $this->host;
$linkURLrewrite = $this->urlRewrite;
if(!empty($this->category)){
?>
<h1><?php echo $this->categoryName;?></h1>
<?php
//print_r($this->category);
    foreach ($this->category as $cat ){
        if ($linkURLrewrite == 1) {
            $link = $this->host . $cat['alias'] . ".html";
        } else {
            $link = $this->host . "view/index/id/" . $cat['id'];
        }
    ?>
    <!--<br />-->
    <a href="<?php echo $link;?>"><?php echo $cat['title'];?></a>
    <?php
    }
}