<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
<?php
$host = $this->host;
$linkURLrewrite = $this->urlRewrite;
if(!empty($this->category)){
?>
<h1><?php echo $this->categoryName;?></h1>
<?php
//print_r($this->category);
    foreach ($this->category as $cat ){
        if ($linkURLrewrite == 1) {
            $link = $this->host . $cat['alias'] . ".html";
        } else {
            $link = $this->host . "view/index/id/" . $cat['id'];
        }
        //if empty image
        if($cat['image'] == "") {
            $image = $host . "images/page_preview.png";
            $imageClass = "withoutPic";
        } else {
            $image = $cat['image'];
            $imageClass = "withPic";
        }
        
    ?>
    <!--<br />-->
    <br />
    <div class="catViewDescWrap">
    <h3><?php echo $cat['title'];?></h3>
    <img src="<?php echo $image ;?>" alt="" class="<?php echo $imageClass;?>" />
    <div style="" class="categoryItemDesc">
        <p><?php echo strip_tags( $cat['description']); ?>...
        </p>
    <a href="<?php echo $link;?>" class="categItem blankLink"  ><?php echo $this->translator->_('Read more');?></a>
    </div>


    </div>
    <?php
    }
}
?>
<br />
