<div class="dropdown relative left-1" style="z-index:9;" title="">
    <div tabindex="0" role="button" class="btn btn-sm min-h-8 h-8 w-8 rounded-full">
        <svg width="12px" height="12px" class="h-2 w-2 fill-current opacity-60 inline-block" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2048 2048"><path d="M1799 349l242 241-1017 1017L7 590l242-241 775 775 775-775z"></path></svg>
    </div>
    <ul id="daisyui-themes-changer" tabindex="0" class="dropdown-content z-[99] p-2 shadow-2xl bg-base-300 rounded-box w-auto">
        <?php
        $daisyuiThemes = '';
        foreach( $this->tailwindConfArray as $theme){
            $unwanted = ['"', ' ', "'"];
            $theme =  str_replace($unwanted, '', $theme);

            $daisyuiThemes .= '<li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-center" aria-label="' . ucfirst($theme) . '" value="' . $theme . '"/></li>';
        }
        echo $daisyuiThemes;
        ?>
    </ul>
</div>