<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
<div class="lb">
<?php
//print_r($this->images);
//print_r($this->thumbs);
//$host = "http://localhost/quickstart/public/";
$host = $this->host;
//print_r($this->thumbs);
foreach ($this->thumbs as $key=>$thumb) {
    echo '<div class="lbImage"><a class="lightbox" href="' . $host . 'images/' . $this->folder . '/' . str_replace("thumb_", "", $thumb) . '"><img align="center" src="' . $host . 'images/' . $this->folder . '/' . $thumb . '" /></a></div>' ;
}

?>

</div>