<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
<?php
$host = $this->host;
//$host = $this->host;
   // echo '<a class="lightbox" href="' . $this->host . 'images/' . $this->folder . '/' . $this->image . '"><img src="' . $this->host. 'images/' . $this->folder . '/' . $this->image . '" /></a>' ;
    //echo '<div style="width:100%;height:100%;"><img  src="' . $this->host. 'images/' . $this->folder . '/' . $this->image . '" height="100%" /></div>' ;
    echo '<img  src="' . $this->host. 'images/' . $this->folder . '/' . $this->image . '" height="100%" width="100%" />' ;
