<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
<ul class=" jd_menu jd_menu_slate grid grid-cols-6 xl:grid-cols-10 justify-items-stretch w-full  text-center">
<?php

$menu_items = $this->menu_items;

$host = $this->host;
$linkType = 'href';
$target = "_self";
$linkURLrewrite = $this->urlRewrite;

foreach(@$this->menus as $menus => $k){

    if ($linkURLrewrite == 1){//if REWRITEURL
        $link = '/pages/' . $k['alias'] . ".html";
    } else {
        $link = '/' . $k['url'];
    }
    echo '<li class="group transition ease-in duration-200 hover:bg-accent rounded pr-2 min-w-fit col-span-12 md:col-span-2 lg:col-span-1 w-full md:w-auto grid grid-cols-12">';
    //generate link if there is such
    if ($k['url'] != '' ) {
        echo '<a class="link text-primary-content col-span-10 p-2" target="' .$target . '" ' . $linkType. '="'  . $link . '" >'.$k['name'].'</a>';
    } else {
        echo '<a class="link text-primary-content col-span-10 p-2" target="' .$target . '" ' . $linkType. '="' . $this->host . '" >'.$k['name'].'</a>';
    }
    //if there is submenu generate submenu links //SUBLEVEL 1
    if ( @$menu_items[$k['item_id']] !== null ){
        echo '<span class="submenu-pointer grid col-span-2 items-center self-center justify-self-end justify-items-center rounded-full text-primary-content right-1 top-1 w-4 h-4 text-xs"></span><ul class="min-w-48 w-full md:w-auto grid grid-cols-12 shadow-lg">';
        foreach($menu_items[$k['item_id']] as $sub => $s){

            if ($linkURLrewrite == 1){
                $link = '/pages/' . $s['alias'] . ".html";
            } else {
                $link = '/' . $s['url'];
            }

            echo '<li id="'.$s['item_id'].'" class="group transition ease-in duration-200 hover:bg-accent hover:bg-accent rounded pr-2 w-full md:w-auto grid grid-cols-12"><a ' . $linkType. '="'  . $link . '"  target="' .$target . '" class="link text-primary-content col-span-10 p-2"   >' . $s['name'] . '</a> ';
            // SUBLEVEL 2
            if ( @$menu_items[$s['item_id']] !== null ) {
                echo '<span class="submenu-pointer grid col-span-2 justify-self-end items-center self-center justify-items-center rounded-full text-primary-content  right-1 top-1 w-4 h-4 text-xs"></span><ul class="min-w-48 w-full md:w-auto grid grid-cols-12 shadow-lg">';
                foreach($menu_items[$s['item_id']] as $sub2 => $s2) {

                    if ($linkURLrewrite == 1) {
                        $link = '/pages/' . $s2['alias'] . ".html";
                    } else {
                        $link = '/' . $s2['url'];
                    }

                    echo '<li id="'.$s2['item_id'].'" class="group transition ease-in duration-200 hover:bg-accent rounded pr-2 w-full md:w-auto grid grid-cols-12"><a ' . $linkType. '="'  . $link . '"  target="' .$target . '" class="link text-primary-content col-span-10 p-2"   >' . $s2['name'] . '</a> ';

                    //SUBLEVEL 3
                    if ( @$menu_items[$s2['item_id']] !== null ) {
                        echo '<span class="submenu-pointer grid col-span-2 justify-self-end items-center self-center justify-items-center rounded-full text-primary-content  right-1 top-1 w-4 h-4 text-xs"></span><ul class="min-w-48 w-full md:w-auto grid grid-cols-12 shadow-lg">';
                        foreach($menu_items[$s2['item_id']] as $sub3 => $s3) {
                            if ($linkURLrewrite == 1) {
                                $link = '/pages/' . $s3['alias'] . ".html";
                            } else {
                                $link = '/' . $s3['url'];
                            }
                            echo '<li id="'.$s3['item_id'].'" class="group transition ease-in duration-200 hover:bg-accent rounded pr-2 w-full md:w-auto grid grid-cols-12"><a ' . $linkType. '="'  . $link . '"  target="' .$target . '" class="link text-primary-content col-span-10 p-2"   >' . $s3['name'] . '</a> ';

                            echo '</li>';
                        }
                        echo '</ul>';
                    }
                    echo '</li>';
                }
                echo '</ul>';
            }
            echo '</li>';
        }
        echo '</ul>';
    }
    echo '</li>';
}
?>
</ul>
<script>
    $('.submenu-pointer').livequery('click', function(e){
        $(e.target).closest('li').trigger('mouseover');
        return false;
    })
</script>
