<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
<div class="cycleDiv">
<?php
$host = $this->host;
//print_r($this->thumbs);
$i =0;
foreach ($this->thumbs as $key=>$thumb) {
if($i== 0 || $i == 4 || $i == 8) {
echo '<div class="cycleSlide" width="900px">';
}
    echo '<img class="cycleImage1" align="center" src="' . $host . 'images/' . $this->folder . '/' .  $thumb . '" />' ;
if($i== 3 || $i == 7 || $i == 11) {
echo '</div>';
}
$i++;
}

?>
</div>
<script type="text/javascript">
$(document).ready(function() {
    $('.cycleDiv').cycle({
    fx:      'fade', 
    timeout: 4000 
	});
});
</script>
