<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
<?php

foreach($this->langs as $lang) {
?>
<a  href="/lang/<?php echo $lang;?>/" value="<?php echo $this->returnUrl;?>" class="langLinks"><img  src="<?php echo $this->hostForImage;?>images/languages/<?php echo $lang;?>.png" /><?php //echo $lang;?></a>&nbsp;

<?php
}