<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
<?php
setlocale(LC_TIME, "fr_FR");
//echo $this->translate->_("Created by: ") . $this->pageinfo['fullname'] . $this->translate->_(", ") . date("d.m.Y, G:H:s", $this->pageinfo['created'] );
echo '<div id="pageinfoDiv" class="blackTheme">' . $this->translate->_("Created by: ") . $this->pageinfo['fullname'] . $this->translate->_(", ") . strftime("%A %d.%B %Y %H:%M",  $this->pageinfo['created'] ) . '</div>';