<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
<?php
 $i=1;
?>

<?php if ($this->pageCount > 1): ?>
  <div id="paginationControl" class="pagination-container grid gap-2 relative">
    <div class="flex gap-2"><i><?php echo $this->translate("Total");?>: <?php echo $this->totalItemCount;?></i>
    </div>

    <div class="flex gap-2"><?php echo $this->translate("PAGE");?><span class="current"><?php echo $this->current;?></span>/<span class="total"><?php echo $this->pageCount;?></span>
    </div>

    <div class="flex gap-2 bg-neutral-content py-4 rounded">
      <!-- Previous page link -->
      <a class="pagback arrows pag_a" href="<?php $this->host;?>creator/paginate-table-manage-pages/tid/<?php echo $this->params['tableId']; ?>/page/<?php echo $this->previous;?>"> <?php echo $this->translate('Back');?></a>

      <!-- Numbered page links -->
      <?php foreach ($this->pagesInRange as $page): ?>
        <?php echo '<!--' . $this->route . '-->';?>
        <?php
        if($page == $this->current){
          $style = "font-weight:bold;text-decoration:none;";
        } else {
          $style = "font-weight:normal;text-decoration:underline;";
        }
        ?>

        <a style="<?php echo $style;?>" class="pag_a" href="<?php $this->host;?>creator/paginate-table-manage-pages/tid/<?php echo $this->params['tableId']; ?>/page/<?= $page; ?>" value="<?= $page; ?>"><?= $page; ?></a> &nbsp;
      <?php endforeach; ?>

      <!-- Next page link -->
      <a class="pagnext arrows pag_a" href="<?php $this->host;?>creator/paginate-table-manage-pages/tid/<?php echo $this->params['tableId']; ?>/page/<?php echo $this->next;?>" ><?php echo $this->translate('Next');?></a>
    </div>
  </div>
<?php
  $i++;
?>
<?php endif; ?>
