<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
<h1 class="searchHeaading">Search results</h1>
<br />
<div id="searchResults">
<?php
$host = $this->host;
//$host = $this->host;

//print_r($this->hits);
//echo $this->currentPageNumber . "**";
if (count($this->hits)) {
    if($this->pageNumber == '1'){//ako je prva strana
        $strKoef = 0;
    } else {
        $strKoef = ($this->pageNumber-1) * $this->itemCountPerPage;    
    }
    
    foreach ($this->hits as $k => $hit) {
        echo ($strKoef + ($k +1) ) . '.<br /><a class="componentLink" href="' . $host . @$hit['url'] . '">  '  . @$hit['title'] . '</a><br />' ;
        echo  @$hit['teaser'] . "" ;
        echo '<div class="horizontalLine" style="width:100%;"></div>';

    }
?>
<br /><br />
<?php echo($this->paginationControl($this->hits, 'Sliding', 'paginatorSearch.phtml', array('params' => array('host' => $this->host, 'what' => $this->keyword) ) )); ?>
<?php
} else {
    echo   "<h2>No results for:" . $this->keyword . "</h2>" ;

}
?>
</div>
