<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
<?php
if(!empty($this->menus)){
?>

<div style="overflow:hidden;height:350px;max-height:350px;background:transparent;color:black;padding:0;margin:0;" id="banner">

<?php
//print_r($this->menus);
$i = 0;

    foreach ($this->menus as $item) {
    $left = 1000*$i;
    ?>
    
    <div class="banners" style="overflow:hidden;display:none;height:100%;position: absolute;margin:0; margin-left:<?php echo $left;?>px; z-index:<?php echo $i;?>; opacity: 1;  width:100%;float:left;" id="banner_00<?php echo $i;?>">
    
    <?php echo $item['output'];?>
    </div>
    
    <?php
    $i++;
    }
    ?>
    
    
    </div>
    
    <div class="banner_paging"  style="width:100%;height:50px;padding:0;margin:0;" id="Slideshow">
    
        <div  class="slideNavig" style="height:10px;">
        
        <img  src="<?php echo $this->host;?>images/dn_banner_arrow_current.png" alt="" id="banner_current"  />
        </div>
        
        <div  class="slideNavig" style="height:50px;margin:0 auto;">
        
        <?php
        $i = 0;
        foreach ($this->menus as $item) {
        ?>
        <h1 style="width:auto;float:left;cursor:pointer;" class="slideLinks" title="<?php echo $i;?>"><?php echo $item['name'] ;?></h1>
        <?php
        $i++;
        }
        ?>
        </div>
    
    
    </div>

<?php
}




