<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
<div>
<?php

//print_r($this->cols);
//print_r($this->table);

foreach ($this->cols as $col ) {
$colone[] = $col['Field'];
}
?>
<a href="<?php echo $this->actions['add'];?>" class="navLinks uniTableAdmin a_add" value="<?php echo $this->tableId;?>"><?php echo $this->addTitle;?></a>
<div class="expanderDiv" value="uta_<?php echo $this->tableId;?>" style="width:17px;height:17px;float:right;border:0px solid #e7e7e7;-moz-border-radius:3px;margin:2px;"></div>
<table id="uta_<?php echo $this->tableId;?>" value="<?php echo $this->tableId;?>" class="universalTableAdmin" cellspacing="0" >
    <?php
    echo '<thead><tr>';
    echo "<th>Chk</th>";
        foreach ($colone as $kolona) {
        echo "<th>" . $kolona . "</th>";
        }
        echo "<th>Action</th>";
    echo '</tr></thead>';
    ?>
    <tbody>
    <?php
    foreach ($this->table as $data) {
    ?>    
    <tr id="<?php echo $data[$colone[0]]?>" class="utaNormal">
        <td width="15px;"><input value="<?php echo $this->tableId;?>" id="chk_<?php echo $data[$colone[0]]?>" class="navLinks uniTableAdmin a_edit" /></td>

        <?php
        foreach ($colone as $kolona) {
        ?>
        <td><?php  echo $data[$kolona];?></td>
        <?php
        }
        ?>
        <td width="150px;"><a value="<?php echo $this->tableId;?>" id="edit_<?php echo $data[$colone[0]]?>" class="navLinks uniTableAdmin a_edit" href="<?php echo $this->actions['edit'];?>" >Edit</a> &nbsp;<a href="<?php echo $this->actions['delete'];?>" id="<?php echo $data[$colone[0]]?>" class="navLinks uniTableAdmin a_delete" value="<?php echo $this->tableId;?>">Delete</a></td>
    </tr>
    <?php
    }
    ?>
    </tbody>
</table>

</div>

<?php echo($this->paginationControl($this->paginator, 'Sliding', 'paginator.phtml')); ?>