<?php
/**
* IDE21 Content Management System
*
* @category   Layouts
* @package    IDE21
*  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
*
*  This file is part of IDE21.
*
*  IDE21 is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
*
*
*
*/
?>
<div id="div_uta_<?php echo $this->tableId;?>">
  <?php
  foreach ($this->cols as $col ) {
    $colone[] = $col['Field'];
  }
  ?>
  <a href="<?php echo @$this->actions['add'];?>" class="navLinks uniTableAdmin a_add btn btn-xs" value="<?php echo $this->tableId;?>"><?php echo $this->translate->_($this->addTitle);?></a>

  <select id="paginationStep_<?php echo $this->tableId;?>" class="paginationStep select select-xs float-right w-10">
    <option>-</option>
    <option>5</option>
    <option >10</option>
    <option>15</option>
    <option>25</option>
  </select>

  <!--<div class="expanderDiv" value="uta_<?php echo $this->tableId;?>" style="width:17px;height:17px;float:right;border:0px solid #e7e7e7;-moz-border-radius:3px;margin:2px;"></div>-->

  <div class="overflow-x-auto my-4">
    <table id="uta_<?php echo $this->tableId;?>" value="<?php echo $this->tableId;?>" class="universalTableAdmin bg-neutral-content text-center table table-xs" cellspacing="0" >
      <?php
      echo '<thead><tr class="text-center">';

      foreach ($colone as $kolona) {
        echo "<th>" . $this->translate(ucfirst($kolona) ) . "</th>";
      }
      echo "<th>" . $this->translate("Action") . "</th>";
      echo '</tr></thead>';
      ?>
      <tbody>
        <?php
        foreach ($this->paginator as $data) {
          ?>
          <tr id="<?php echo $data[$colone[0]]?>" class="utaNormal">
            <?php
            foreach ($colone as $kolona) {
              ?>
              <td><?php  echo substr($data[$kolona], 0, 30) ;?></td>
              <?php
            }
            ?>
            <td>
              <a value="<?php echo @$this->tableId;?>" id="edit_<?php echo @$data[$colone[0]]?>" class="navLinks uniTableAdmin a_edit currentTitle1 inline-block" href="<?php echo @$this->actions['edit'];?>" title="" >
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                  <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
                </svg>
                <div class="hidden">Enter details</div>
              </a>
              <a href="<?php echo @$this->actions['delete'];?>" id="<?php echo @$data[$colone[0]]?>" class="navLinks uniTableAdmin a_delete inline-block" value="<?php echo @$this->tableId;?>">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                  <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                </svg>
              </a>
            </td>
          </tr>
          <?php
        }
        ?>
      </tbody>
    </table>
  </div>

  <?php echo($this->paginationControl($this->paginator, 'Sliding', 'paginator.phtml', array('params' => array('tableId' => $this->tableId, 'translate' => $this->translate) ) )); ?>
</div>
