<?php
/**
 * IDE21 Content Management System
 *
 * @category   CreatorController
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="generator" content="NeT">
  <title> Page not found!</title>
  <link rel="shortcut icon" type="image/x-icon" href="/images/ide21logo.svg">
  <link href="/css/tailwind.output.css" rel="stylesheet" type="text/css" />
</head>
<body class="p-0 m-0 w-dvh h-dvh bg-neutral-100">
  <div class="absolute top-0 left-0 w-full h-full bg-neutral-100">
    <h1 class="text-2xl md:text-5xl font-bold text-white w-full text-center absolute top-12 bg-neutral">404 - Page not found!</h1>
    <img src="/images/ide21logo.svg" height="100%" class="w-full h-full object-cover lg:object-contain" >
  </div>
</body>
</html>
