<?php
/**
 * CMS-IDE Visual CMS
 *
 * @category   Layouts
 * @package    CMS-IDE
 *  Copyright (C) 2010-2021  Nebojsa Tomic
 *  
 *  This file is part of CMS-IDE.
 *     
 *  CMS-IDE is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 3 of the License, or (at your option) any later version.
 *
 *  CMS-IDE is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * 
 * 
 */
 ?>
<?php
$pid = $this->pid;

if ($pid == ""){
    $xmlFile = "config.xml";
} else {
    $xmlFile = "config_" . $pid . ".xml";
}
?>
<!--<script type="text/javascript" src="<?php echo $this->host;?>JS/cu3er/js/swfobject/swfobject.js"></script>-->

<script type="text/javascript">
		var flashvars = {};
		flashvars.xml = absoluteUrl + "JS/cu3er/<?php echo $xmlFile;?>";
		//flashvars.font = "font.swf";
		var attributes = {};
		attributes.wmode = "transparent";
		attributes.id = "slider";
		swfobject.embedSWF(absoluteUrl + "JS/cu3er/cu3er.swf", "cu3er-container", "850", "245", "9", absoluteUrl + "JS/cu3er/expressInstall.swf", flashvars, attributes);
</script>


<div id="cu3er-container" style="width:850px;height:255px;">
    <a href="http://www.adobe.com/go/getflashplayer">
        <img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player" />
    </a>
</div>