<?php
/**
 * CMS-IDE Visual CMS
 *
 * @category   Layouts
 * @package    CMS-IDE
 *  Copyright (C) 2010-2021  Nebojsa Tomic
 *  
 *  This file is part of CMS-IDE.
 *     
 *  CMS-IDE is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 3 of the License, or (at your option) any later version.
 *
 *  CMS-IDE is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * 
 * 
 */
 ?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
   <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->host;?>favicon.ico" />
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="generator" content="NeT">
  
  
  
  <title>Creator Login</title>

    <style type="text/css">
        
    #loginform fieldset {background:white;opacity:0.9;margin-bottom:20px;border-radius:15px;font-family:Arial;font-size:12px;padding:20px;}
    #loginform input {color:#000 !important;margin-bottom:5px;width: 100%;padding:5px;padding-left:10px;padding-right:10px;opacity:0.9;-moz-border-radius:15px;font-family:Arial;font-size:12px;color:white;}
    #loginform input[type=submit]{margin-left: 10px;}
    /*#loginform input[type=submit]:hover {padding:5px;padding-left:10px;padding-right:10px;background:blue;opacity:0.9;-moz-border-radius:15px;font-family:Arial;font-size:12px;color:white;}*/

    #loginform dd {margin:0px;margin-top:-16px;margin-left:70px}
 
    </style>
  <link rel="stylesheet" href="<?php echo $this->host;?>CSS/uniform/css/uniform.aristo.css" media="screen" />
  <script type="text/javascript" src="<?php echo $this->host;?>JS/jquery/jquery-1.3.2.min.js"></script>   
  <script type="text/javascript"  src="<?php echo $this->host;?>JS/uniform/jquery.uniform.js"></script>

  </head>
  <body>
    <div style="position:absolute;top:0;left:0;width:100%;height:100%;z-index:9;background:black;">
    <img src="<?php echo $this->host;?>images/loginBg.jpg" height="100%" />
    </div>
    
    <div style="position:relative;top:50px;width:300px;height:300px;z-index:999999;margin:0 auto;">
    <?php
    echo $this->form;
    ?>
    </div>
      <script type="text/javascript" >
      $("select, input").not("#submit").uniform();
  </script> 
  </body>
</html>