<?php
/**
 * CMS-IDE Visual CMS
 *
 * @category   Layouts
 * @package    CMS-IDE
 *  Copyright (C) 2010-2021  Nebojsa Tomic
 *  
 *  This file is part of CMS-IDE.
 *     
 *  CMS-IDE is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 3 of the License, or (at your option) any later version.
 *
 *  CMS-IDE is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * 
 * 
 */
 ?>
 <?php require("css_browser_selector.php"); ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd" >
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" class="<?php echo css_browser_selector() ?>">
    <head>
            <meta name="keywords" content="<?php echo $this->meta_description;?>" />
        <meta name="description" content="<?php echo $this->meta_description;?>" />
        <meta name="generator" content="NeT" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />                
        <title><?php echo $this->title;?> - <?php echo $this->version;?> </title>		
    <style type="text/css">        
        body{min-width:1280px;font-size:11px ;font-family:Arial;/* background:url(<?php echo $this->host;?>images/bgBody.png) no-repeat center;*/}
        li {font-size:11px ;font-family:Arial;}
        #rotate div.creatorDiv{font-size:12px;font-family:Arial;}        
        .draggable {cursor:pointer; position:absolute;width: auto; min-height: 25px;height:auto; background: transparent; padding: 0px;float:left;color: black; overflow:hidden;}
        .draggable:hover {cursor:move; opacity:0.7;}
        .container {  padding: 0px; }
        .templateDiv {position:absolute;border:0px solid green;z-index:0;}
        #fontBigger{width:30px;height:30px;background:transparent;}
        #fontSmaller{width:30px;height:30px;background:transparent;}
        #objProperties input{height:15px;width:50px;margin:1px; }
        #rotate{height:auto; font:12px normal Arial;background:silver;}
        #rotate div{height:auto; font:12px normal Arial;}
        #dialogDiv{display:none;position:relative;left:0 !important;top:0 !important;padding:15px 25px 15px 15px;width:500px;height:auto;background:silver;z-index:999999;border:1px solid #AAAAAA;-moz-border-radius:5px;-webkit-border-radius:5px;}
        .ui-dialog {z-index:999998;}
        .ui-dialog .ui-dialog-titlebar-close {height: 25px; margin: -10px 0 0;padding: 1px;position: absolute;right: 0.3em;top: 40%;width: 25px;}
        .ui-widget-overlay {background: url("images/ui-bg_flat_0_aaaaaa_40x100.png") repeat-x scroll 50% 50% #000000 !important;opacity: 0.5 !important;z-index: 999991 !important;}
        span.ui-button-text{display:none !important;}
        #closeDialogDiv{width:18px;height:18px;background:url(<?php echo $this->host;?>images/interface/closeB.png) no-repeat;text-align:center;float:right;}
        #containerRadnePovrsine {width:100%;height:auto;}
        #droppable { position:relative;z-index:2;top:0;width:70%; height: auto; min-height:900px;background: transparent;  padding: 0px; border:2px dotted lightblue;margin:0 auto;}
        #droppable2 { position:relative;z-index:2;float:left;left:0;top:0;min-width: 100%;width:100%; height: auto; min-height:100%;background: blue;  padding: 0px; border:2px dotted lightblue;}

        #templateMask { position:absolute;z-index:2;top:0;width:70%; height: auto; min-height:900px;background: transparent;  padding: 0px; border:0px dotted red;margin:0 auto;}

        #penPointer{display:none;position:absolute;top:0;left:0;width:65px;height:65px;z-index:199998;background:url(<?php echo $this->host;?>images/interface/Pen.png) no-repeat;}
        #downPointer{display:none;position:absolute;top:0;left:0;width:65px;height:65px;z-index:199998;background:url(<?php echo $this->host;?>/images/interface/down.png) no-repeat;}
        #toolbox {float:left;width:100px;height:auto;}       
        #toggleProperties {opacity:0.8;position:fixed;padding:5px;text-align:center;font-weight:bold;cursor:pointer;left:5px;top:5px;width:20px;height:20px;background:silver url(<?php echo $this->host;?>images/interface/toggleProperties.png) no-repeat center;z-index:999997;border:1px solid #e7e7e7;-moz-border-radius:5px;-webkit-border-radius:5px;}        
        #newItem {opacity:0.8;position:fixed;padding:5px;text-align:center;color:yellow;font-weight:bold;cursor:pointer;right:85px;top:5px;width:20px;height:20px;background:silver url(<?php echo $this->host;?>images/interface/add.gif) no-repeat center;;z-index:999997;border:1px solid #e7e7e7;-moz-border-radius:5px;-webkit-border-radius:5px;}
        #cloneItem {opacity:0.8;position:fixed;padding:5px;text-align:center;color:yellow;font-weight:bold;cursor:pointer;right:85px;top:38px;width:20px;height:20px;background:silver url(<?php echo $this->host;?>images/interface/add.gif) no-repeat center;;z-index:999997;border:1px solid #e7e7e7;-moz-border-radius:5px;-webkit-border-radius:5px;}
        #moveProps {opacity:0.8;position:fixed;padding:5px;text-align:center;color:yellow;font-weight:bold;cursor:pointer;right:5px;top:38px;width:60px;height:20px;background:silver;z-index:999997;border:1px solid #e7e7e7;-moz-border-radius:5px;-webkit-border-radius:5px;}
        #rightB {cursor:pointer;border:0;width:20px;height:15px;background:silver url(<?php echo $this->host;?>images/interface/arrow_right.png) no-repeat center;}
        #leftB {cursor:pointer;border:0;width:20px;height:15px;background:silver url(<?php echo $this->host;?>images/interface/arrow_left.png) no-repeat center;}
        #upB {cursor:pointer;border:0;width:20px;height:15px;background:silver url(<?php echo $this->host;?>images/interface/arrow_up.png) no-repeat center;-moz-border-radius:5px;-webkit-border-radius:5px;}
        #downB {cursor:pointer;border:0;width:20px;height:15px;background:silver url(<?php echo $this->host;?>images/interface/arrow_down.png) no-repeat center;-moz-border-radius:5px;-webkit-border-radius:5px;}


        #logout {opacity:0.8;position:fixed;padding:5px;text-align:center;color:yellow;font-weight:bold;cursor:pointer;right:5px;top:5px;width:20px;height:20px;background:silver url(<?php echo $this->host;?>images/interface/logout.gif) no-repeat center;z-index:999997;border:1px solid #e7e7e7;-moz-border-radius:5px;-webkit-border-radius:5px;}
        #delButton {opacity:0.8;position:fixed;padding:5px;text-align:center;color:yellow;font-weight:bold;cursor:pointer;right:45px;top:5px;width:20px;height:20px;background:silver url(<?php echo $this->host;?>images/interface/note_delete.gif) no-repeat center;;z-index:999997;border:1px solid #e7e7e7;-moz-border-radius:5px;-webkit-border-radius:5px;}
        #helpButton {opacity:0.8;position:fixed;padding:5px;text-align:center;color:yellow;font-weight:bold;cursor:pointer;right:125px;top:5px;width:20px;height:20px;background:silver url(<?php echo $this->host;?>images/interface/help.png) no-repeat center;;z-index:999997;border:1px solid #e7e7e7;-moz-border-radius:5px;-webkit-border-radius:5px;}
        #helpDiv{opacity:0.8;display:none;position:fixed;padding:5px;text-align:center;color:white;font-size:15px;cursor:pointer;right:165px;top:5px;width:500px;height:50px;background:silver ;z-index:999997;border:1px solid #e7e7e7;-moz-border-radius:5px;-webkit-border-radius:5px;}
#updateContentButton {border: 1px solid #E7E7E7; color: yellow;cursor: pointer;font-weight: bold; height: 20px;opacity: 0.8; padding: 5px;position: fixed;right: 125px;text-align: center;top:40px; width: 20px;z-index: 999997;}        
        #toggleProperties:hover {opacity:0.9;position:fixed;padding:5px;text-align:center;font-weight:bold;cursor:pointer;left:5;top:5;width:20px;height:20px;background:silver url(<?php echo $this->host;?>images/interface/toggleProperties.png) no-repeat center;z-index:999997;border:1px solid #e7e7e7;-moz-border-radius:5px;-webkit-border-radius:5px;}        
        #newItem:hover {opacity:0.9;position:fixed;padding:5px;text-align:center;color:yellow;font-weight:bold;cursor:pointer;right:85px;top:5px;width:20px;height:20px;background:silver url(<?php echo $this->host;?>images/interface/add.gif) no-repeat center;;z-index:999997;border:1px solid #e7e7e7;-moz-border-radius:5px;-webkit-border-radius:5px;}
        #logout:hover {opacity:0.9;position:fixed;padding:5px;text-align:center;color:yellow;font-weight:bold;cursor:pointer;right:5px;top:5px;width:20px;height:20px;background:silver url(<?php echo $this->host;?>images/interface/logout.gif) no-repeat center;z-index:999997;border:1px solid #e7e7e7;-moz-border-radius:5px;-webkit-border-radius:5px;}
        #delButton:hover {opacity:0.9;position:fixed;padding:5px;text-align:center;color:yellow;font-weight:bold;cursor:pointer;right:45px;top:5px;width:20px;height:20px;background:silver url(<?php echo $this->host;?>images/interface/note_delete.gif) no-repeat center;;z-index:999997;border:1px solid #e7e7e7;-moz-border-radius:5px;-webkit-border-radius:5px;}
        #contProperties {position:fixed;right:0;bottom:0px;z-index:199999;width:800px;height:auto;min-height:100px;border:0px solid green;}
        #contProperties *{font-family:Arial;font-size:12px!important;}
        #propertiesLeft {float:left;width:400px;border:0px solid green;display:none;}
        #properties {float:right;width:800px;height:300px;font-family:Arial;font-size:12px; display:none;}
        #footer {float:left;width:100%;height:auto;}        
        #tooltip{position:absolute;left:0;top:0;z-index:999999;background:#CCCCCC url(http://net.freehostrocket.com/images/ui-bg_highlight-soft_75_cccccc_1x100.png) repeat-x;-moz-border-radius:5px;width:200px;height:auto;min-height:50px;color:black;font-weight:bold;font-size:15px;;padding:20px;border:1px solid #555555;}       
        #ajax-loader{display:none;position:absolute;left: 860px; top: 340px;width:70px;height:70px;background:transparent url(<?php echo $this->host;?>images/ajax-loader.gif) no-repeat;z-index:999999;}
        .ajax-loader{display:none;}
        #adminAjaxLoader {display:none;width:70px;height:70px;background:transparent;margin:0 auto;}        
        #content {}
        .a_delete {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/note_delete.gif) no-repeat;padding-left:20px;cursor:pointer;color:#555555;font-family:Arial;font-size:12px; }
        .a_preview {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/image.gif) no-repeat;padding-left:20px;cursor:pointer;color:#555555;font-family:Arial;font-size:12px;}
        .a_refresh {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/refresh.gif) no-repeat;padding-left:20px;cursor:pointer;color:#555555 ;font-family:Arial;font-size:12px;}
        .a_save {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/save.gif) no-repeat;padding-left:20px;cursor:pointer;color:#555555 ;font-family:Arial;font-size:12px; }
        .a_save_new {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/save_new.gif) no-repeat;padding-left:20px;cursor:pointer;color:#555555 ;font-family:Arial;font-size:12px; }
        .a_new {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/new.gif) no-repeat;padding-left:25px;cursor:pointer;color:#555555;font-family:Arial;font-size:12px; }
        .a_open {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/open.gif) no-repeat;padding-left:20px;cursor:pointer;color:#555555 ;font-family:Arial;font-size:12px; }
        .a_edit {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/edit.gif) no-repeat;padding-left:20px;cursor:pointer;color:#555555 ;font-family:Arial;font-size:12px; }
        .a_add {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/add.gif) no-repeat;padding-left:20px;cursor:pointer;color:#555555 ;font-family:Arial;font-size:12px; }
        .a_content {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/content.gif) no-repeat;padding-left:25px;cursor:pointer;color:#555555;font-family:Arial;font-size:12px; }
        .a_generateCache {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/generate_cache.gif) no-repeat;padding-left:25px;cursor:pointer;color:#555555;font-family:Arial;font-size:12px; }
        .a_emptyCache {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/empty_cache.gif) no-repeat;padding-left:25px;cursor:pointer;color:#555555;font-family:Arial;font-size:12px; }
        .a_backup {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/backup.png) no-repeat 0px -2px;padding-left:25px;cursor:pointer;color:#555555;font-family:Arial;font-size:12px; }
        .a_access {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/access.png) no-repeat ;padding-left:25px;cursor:pointer;color:#555555;font-family:Arial;font-size:12px; }
        .a_ftp{text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/package_go.png) no-repeat ;padding-left:25px;cursor:pointer;color:#555555;font-family:Arial;font-size:12px; }

        /*manage all pages style*/
        .a_published {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/published.png) no-repeat ;padding-left:25px;cursor:pointer;color:#555555;font-family:Arial;font-size:12px; }
        .a_unpublished {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/unpublished.png) no-repeat ;padding-left:25px;cursor:pointer;color:#555555;font-family:Arial;font-size:12px; }
        .a_previewManage {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/eye.png) no-repeat;padding-left:20px;cursor:pointer;color:#555555;font-family:Arial;font-size:12px;}
        .a_deleteManage {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/bin.png) no-repeat;padding-left:20px;cursor:pointer;color:#555555;font-family:Arial;font-size:12px; }
        .a_chkAccess1 {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/key.png) no-repeat;padding-left:20px;cursor:pointer;color:#555555;font-family:Arial;font-size:12px;}
        .a_chkAccess0 {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/group.png) no-repeat;padding-left:20px;cursor:pointer;color:#555555;font-family:Arial;font-size:12px; }
        .deleteAll {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/bin.png) no-repeat;padding-left:20px;cursor:pointer;color:#555555;font-family:Arial;font-size:12px; }
        .a_clear {text-decoration:none;font-style:italic;color:#555555}
        .a_redraw {text-decoration:none;color:#555555}
        .a_logout {text-decoration:none;color:white}        
        
        .a_delete:hover {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/note_delete.gif) no-repeat;padding-left:20px;cursor:pointer;color:#3d4752 }
        .a_preview:hover {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/image.gif) no-repeat;padding-left:20px;cursor:pointer; color:#3d4752}
        .a_refresh:hover {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/refresh.gif) no-repeat;padding-left:20px;cursor:pointer;color:#3d4752 }
        .a_save:hover {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/save.gif) no-repeat;padding-left:20px;cursor:pointer;color:#3d4752  }
        .a_save_new:hover {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/save_new.gif) no-repeat;padding-left:20px;cursor:pointer;color:#3d4752  }
        .a_new:hover {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/new.gif) no-repeat;padding-left:25px;cursor:pointer;color:#3d4752 ;}
        .a_open:hover {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/open.gif) no-repeat;padding-left:20px;cursor:pointer;color:#3d4752 }
        .a_edit:hover {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/edit.gif) no-repeat;padding-left:20px;cursor:pointer;color:#3d4752 }
        .a_content:hover {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/content.gif) no-repeat;padding-left:25px;cursor:pointer;color:#3d4752 }
        .a_add:hover{text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/add.gif) no-repeat;padding-left:20px;cursor:pointer;color:#3d4752 ; }
        .a_generateCache:hover {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/generate_cache.gif) no-repeat;padding-left:25px;cursor:pointer;color:#3d4752 ; }
        .a_emptyCache:hover {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/empty_cache.gif) no-repeat ;padding-left:25px;cursor:pointer;color:#3d4752 ; }
        .a_backup:hover {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/backup.png) no-repeat 0px -2px;padding-left:25px;cursor:pointer;color:#3d4752 ; }
        .a_access:hover {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/access.png) no-repeat ;padding-left:25px;cursor:pointer;color:#3d4752 ; }
        .a_weightUp {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/arrow_up.png) no-repeat 0px -2px;padding-right:25px;cursor:pointer;color:#3d4752 ;margin-right:30px; }
        .a_weightDw {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/arrow_down.png) no-repeat ;padding-right:25px;cursor:pointer;color:#3d4752 ; margin-right:35px;}
        .a_params {text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/params.png) no-repeat ;padding-right:16px;cursor:pointer;color:#3d4752 ; }

        .a_clear:hover {text-decoration:none;color:#3d4752}
        .a_redraw:hover {text-decoration:none;color:#3d4752}
        #banner{min-height:200px}
        #banner_current{display:none;}
        .objContent{}
        .activeObject{opacity:1;border:1px solid red;}
        .inactiveObject{opacity:0.2;filter:alpha(opacity=20)}
        .universalTableAdmin {border:1px solid #555555;width:100%;min-height:300px;margin-bottom: 10px;margin-top: 10px;}
        .universalTableAdmin th {border:1px solid silver;background:white;text-align:center;}
        .universalTableAdmin td{text-align:center;}
        #rotate div.expanderDiv {background:transparent url(<?php echo $this->host;?>images/interface/expander.gif) no-repeat;cursor:pointer; }
        #rotate div.expanderDivClosed {background:transparent url(<?php echo $this->host;?>images/interface/expanderClosed.gif) no-repeat;cursor:pointer; }
        #rotate div.expanderFullScr {background:transparent url(<?php echo $this->host;?>images/interface/expanderFullScr.gif) no-repeat;cursor:pointer; }
#rotate .fsbutton {height: 20px;width: 20px;display:block;background:transparent url(<?php echo $this->host;?>images/interface/expanderFullScr.gif) no-repeat;cursor:pointer; }

        /*.universalTableAdmin tr {text-align:center;background:#f4f4f4;}*/
        .utaNormal {background:#f4f4f4;text-align:center;}
        .utaHover {background:#cccccc;text-align:center;}
        input{-moz-border-radius:5px;-webkit-border-radius:5px;border:1px solid #cccccc;background:#E6E6E6;font-size:12px;font-family:Arial;}
        textarea{background:#E6E6E6;border:1px solid #cccccc;font-size:12px;font-family:Arial;}
        select{background:#E6E6E6;border:1px solid #cccccc;width:150px;font-size:12px;font-family:Arial;}
        input[type=checkbox]{background:#E6E6E6;border:1px solid #cccccc;}

        #rotate input{border:1px solid #cccccc;background:#E6E6E6;font-size:12px;font-family:Arial;}
        #rotate label{font-size:12px;font-family:Arial;}
        #rotate div label{font-size:12px;font-family:Arial;}
        #rotate div div{font-size:12px;font-family:Arial;}
        #rotate div a{font-size:12px;font-family:Arial;}
        #rotate textarea{background:#E6E6E6;border:1px solid #cccccc;}
        #rotate select{background:#E6E6E6;border:1px solid #cccccc;width:180px;font-size:12px;font-family:Arial;}
        #rotate input[type=checkbox]{-moz-border-radius:5px;-webkit-border-radius:5px;background:#E6E6E6;border:1px solid #cccccc;}
        #rotate input[type=submit]{-moz-border-radius:5px;-webkit-border-radius:5px;background:#555555;border:1px solid #cccccc;color:#f4f4f4;height:25px;margin-top:5px;}
        #rotate input[type=submit]:hover{-moz-border-radius:5px;-webkit-border-radius:5px;background:#f4f4f4;border:1px solid #cccccc;color:#555555;height:25px;margin-top:5px;}
        input[type=submit]:hover{-moz-border-radius:5px;-webkit-border-radius:5px;background:#f4f4f4;border:1px solid #cccccc;}
        #rotate #langName{background:rgb(196, 213, 230) none repeat scroll 0% 0%;text-align:left;border-radius:15px;width: auto;min-width: 100px;}
        .pagnext{text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/a_next.png) no-repeat right;padding-right:20px;cursor:pointer;color:#3d4752 }        
        .pagback{text-decoration:none;background:transparent url(<?php echo $this->host;?>images/interface/a_previous.png) no-repeat;padding-left:20px;cursor:pointer;color:#3d4752 }        
        #rotate #tree div{margin-left:-15px;margin-right:0px;padding:0px;width:15px;height:15px;background-image:url(<?php echo $this->host;?>images/treeview-default.gif);}

        #rotate #tree li.expandable div{background-position:-80px -2px;}
        #rotate #tree li.collapsable div{background-position:0px -111px;}
        #fragment-1 span {float: left;}
        #fragment-1 input {border-radius:5px;}
        #fragment-1 span.cl {clear:both;}
        #fragment-1 span.cl +span  {float: right;}
        /*#fragment-1 #tableFr1 tbody > tr{display:block;margin-bottom:10px;}*/
        #fragment-1 #tableFr1 td{vertical-align: top;text-align: left;}
        #fragment-1 .mceLayout tbody tr{display:table;margin-bottom:0px;}
        /*div.selector{padding:0 !important;background-position:0px -160px !important;}*/
        div.selector span {padding-right:0px !important;padding-left:3px !important;/**/margin-left: 0px;}
        #fragment-1 dd {display: block;float: right; position: relative;width: auto;}
        #chooseLangAdminForm {display: block;float: right; position: absolute;right: 0; top: -15px;width: auto;}
        .cssjswrapp{background:silver; padding:30px;padding-top:20px;padding-bottom:20px;height:100%;display:block; position:relative;}
        .cssjswrapp2{background:silver; padding:10px;padding-top:20px;padding-bottom:20px;height:100%;display:block; position:relative;}

        div.help {border-radius:5px;}
        #imagesContainer, #imageFoldersShow {float:left;}
        .ui-dialog .ui-dialog-titlebar-close span {display: block;margin: -2px !important;width: 15px;}
        .ui-dialog{position: fixed !important;}
        .ui-dialog legend{margin-left:10px;float: left;margin-left: 5px;}
        .marginBottom5{margin-bottom:5px; float: left;}
        #addMenuItForm{float:left;}
        #dialogDivImages{background:silver;}
        #TB_window {z-index:999998 !important;}
    </style>
    <link rel="stylesheet" href="<?php echo $this->host;?>CSS/jdMenu/blue/jquery.jdMenu.css" type="text/css" />
    <link rel="stylesheet" href="<?php echo $this->host;?>CSS/default.css" type="text/css" /><!--CSS written in admin panel-->
    <link rel="stylesheet" href="<?php echo $this->host;?>CSS/backend.css" type="text/css" /><!--CSS written for the admin panel-->    
    <!--TABLE GRID STYLES-->
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->host;?>JS/jqgrid/themes/redmond/jquery-ui-1.7.1.custom.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->host;?>JS/jqgrid/themes/ui.jqgrid.css" />    
    <!--treeView-->
    <link rel="stylesheet" href="<?php echo $this->host;?>CSS/treeView/jquery.treeview.css" type="text/css" />
    <link rel="stylesheet" href="<?php echo $this->host;?>CSS/treeView/screen.css" type="text/css" />
    <!--lightBox-->
    <link rel="stylesheet" href="<?php echo $this->host;?>CSS/lightbox/jquery.lightbox-0.5.css" type="text/css" />
    <link rel="stylesheet" href="<?php echo $this->host;?>CSS/lightbox/thickbox.css" type="text/css" media="screen" />
    <!--color picker-->
    <link rel="stylesheet" media="screen" type="text/css" href="<?php echo $this->host;?>CSS/colorpicker.css" />
    <link rel="stylesheet" href="<?php echo $this->host;?>CSS/default.css" type="text/css" /><!--CSS written in admin panel-->
    <link rel="stylesheet" href="<?php echo $this->host;?>CSS/backend.css" type="text/css" /><!--CSS written for the admin panel-->
    <!--<link type="text/css" href="http://jqueryui.com/latest/themes/base/ui.all.css" rel="stylesheet" />-->
    <link type="text/css" href="<?php echo $this->host;?>CSS/jqUI/ui.all.css" rel="stylesheet" />
    <link type="text/css" href="<?php echo $this->host;?>CSS/defaultWidgets.css" rel="stylesheet" />
    <!--themes for the objects-->
    <link type="text/css" href="<?php echo $this->host;?>CSS/themes.css" rel="stylesheet" />
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->host;?>favicon.ico" />
    <link rel="stylesheet" href="<?php echo $this->host;?>CSS/uniform/css/uniform.aristo.css" media="screen" />   
    <!-- Add fancyBox -->
<link rel="stylesheet" href="<?php echo $this->host;?>fancybox/2/jquery.fancybox.css" type="text/css" media="screen" />

    <script type="text/javascript" >
    absoluteUrl = "<?php echo $this->hostRW;?>";
    absoluteUrl2 = "<?php echo $this->host;?>";
    </script>
    <!--<script type="text/javascript" src="<?php echo $this->host;?>JS/jquery/jquery-2.0.2.min.js"></script>-->
    <!--<script src="http://code.jquery.com/jquery-2.0.2.js"></script>-->
    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
<script src="http://code.jquery.com/jquery-migrate-1.2.1.js"></script>
    <!--<script type="text/javascript" src="<?php echo $this->host;?>JS/combinedAll.js"></script>-->
    <script type="text/javascript" src="<?php echo $this->host;?>JS/jquery/jquery.ui.js"></script>
    <script type="text/javascript" src="<?php echo $this->host;?>JS/jquery/jquery.livequery.js"></script>
    <script type="text/javascript" src="<?php echo $this->host;?>JS/jquery/colorpicker.js"></script>
    <script type="text/javascript" src="<?php echo $this->host;?>JS/jquery/ui.draggable.js"></script>
    <script type="text/javascript" src="<?php echo $this->host;?>JS/jquery/ui.droppable.js"></script>
    <script type="text/javascript" src="<?php echo $this->host;?>JS/jquery/ui.resizable.js"></script>

     <script type="text/javascript" src="<?php echo $this->host;?>JS/jquery/jquery.jdMenu.js"></script>
      <script type="text/javascript" src="<?php echo $this->host;?>JS/jquery/jquery.treeview.js"></script>
    <script type="text/javascript" src="<?php echo $this->host;?>JS/jquery/jquery.form.js"></script>
    
        <script type="text/javascript" src="<?php echo $this->host;?>JS/jquery/alajax.js"></script>
    <!--dialog-->
    <script type="text/javascript" src="<?php echo $this->host;?>JS/jquery/ui.dialog.js"></script>
    <script type="text/javascript" src="<?php echo $this->host;?>JS/jquery/ui.position.js"></script>
    <!--TABLE GRID JS-->
    <!-- <script type="text/javascript" src="<?php echo $this->host;?>JS/jqgrid/js/jquery-ui-1.7.1.custom.min.js" ></script>
   <script type="text/javascript" src="<?php echo $this->host;?>JS/jqgrid/js/jquery.layout.js" ></script>
    <script type="text/javascript" src="<?php echo $this->host;?>JS/jqgrid/js/i18n/grid.locale-en.js" ></script>
    <script type="text/javascript" src="<?php echo $this->host;?>JS/jqgrid/js/jquery.jqGrid.min.js" ></script>
    <script type="text/javascript" src="<?php echo $this->host;?>JS/jqgrid/js/jquery.tablednd.js" ></script>
    -->
    <script type="text/javascript" src="<?php echo $this->host;?>JS/jqgrid/js/jquery.contextmenu.js" ></script>
    <script type="text/javascript" src="<?php echo $this->host;?>JS/jquery/thickbox.js"></script>        
    <script language="JavaScript" type="text/javascript" src="<?php echo $this->host;?>JS/wysiwyg/tiny_mce/tiny_mce.js"></script>          
    <!--Cycle-->
    <!--<script type="text/javascript" src="<?php echo $this->host;?>JS/slide/jsCycle.js" ></script>  --> 
    <script type="text/javascript"  src="<?php echo $this->host;?>JS/uniform/jquery.uniform.js"></script> 
    <script type="text/javascript" src="<?php echo $this->host;?>JS/jqtransformplugin/jquery.jqtransform.js"></script>

    <script type="text/javascript" src="<?php echo $this->host;?>fancybox/2/jquery.fancybox.js"></script>
        <?php echo $this->headScript(); ?>  
    
    </head>
    <body style="font-size:11px ;font-family:Arial;">
        <div id="ajax-loader"></div> 
        <div id="dialogDiv"></div>     
<!--<div id="bodyBack" style="position: fixed; display: block; width: 100%; height: 100%;top:0;left:0;z-index:0;">
  <img class="body2be" src="<?php $bgParts = explode(")", $this->templateBodyBackground); echo str_replace("url(", "" ,$bgParts[0]);?>" width="100%">
</div> -->
        <div id ="container">          
          <!--<div style="position:relative;width:1280px;height:100%;margin:0 auto;">-->
          <div id="content">
              <?php 
                  echo $this->layout()->content; 
              ?>	
          </div>
          <!--</div>-->    
        </div>  
        <script type="text/javascript" src="<?php echo $this->host;?>JS/codepressFix.js" ></script>
        <script type="text/javascript" src="<?php echo $this->host;?>JS/codepress/codepress.js" ></script>
       <script type="text/javascript">
	$(document).ready(function() {
	$('select, input, textarea').livequery(function(){$(this).uniform();}); 
	});
</script>     
 <!--<iframe id="ide21-creator" src="/ide21_creator/interface" title="Tools and properties" style="width: 300px;height: 100vh; position: fixed; top: 0; left: 0;"></iframe> -->
    </body>    
</html>