<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
<script type="text/javascript" >
$('#adminAddLanguageForm').ajaxForm(function(data){
    jsin = eval("(" + data + ")" );
    languages = jsin["out"]["languages"] ;
    Message = jsin["out"]["message"] ;
    comboFill = jsin["out"]["comboFill"] ;

    $('#dialogDiv').remove();
    
    $('#languageDiv').html(languages);
    ajaxEmitMessage(Message);
    setTimeout("clickMask()", 1000); //closing all          
    $('#langName').append(comboFill);
});
</script>
