<?php
/**
 * CMS-IDE Visual CMS
 *
 * @category   Layouts
 * @package    CMS-IDE
 *  Copyright (C) 2010-2021  Nebojsa Tomic
 *  
 *  This file is part of CMS-IDE.
 *     
 *  CMS-IDE is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 3 of the License, or (at your option) any later version.
 *
 *  CMS-IDE is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * 
 * 
 */
 ?>
 <div id="cornerPropDiv" class="grid gap-2 items-center">
  <div>
    Corner style:
    <select id="chooseCornerStyle" class="select select-xs w-full">
      <option>round</option>
      <option>dog</option>
      <option>sharp</option>
      <option>bevel</option>
      <option>notch</option> 
      <option>bite</option>
      <option>cool</option>
      <option>slide</option>
      <option>fray</option>
      <option>wicked</option>
      <option>sculpt</option>
      <option>long</option>                      
    </select>
  </div>
  <div>
    Corner orientation:
    <select id="chooseCornerOrientation" class="select select-xs w-full">
      <option></option>
      <option>top</option>
      <option>bottom</option>
    </select>
  </div>
  <div>
    Radius(px):<input class="input input-sm w-full" type="text" id="cornerParamRadius" /> 
  </div>
  <div>
    Container BG:<input class="input input-sm w-full" type="text" id="cornerParamBg" />
  </div>
  <div class="">
    <input class="btn btn-xs btn-secondary w-full" type="submit" value="Apply" id="cornerParamButton" />
  </div>
</div>