<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
 <div id="cornerPropDiv" class="grid gap-2 items-center">
  <div>
    Corner style:
    <select id="chooseCornerStyle" class="select select-xs w-full">
      <option>round</option>
      <option>dog</option>
      <option>sharp</option>
      <option>bevel</option>
      <option>notch</option> 
      <option>bite</option>
      <option>cool</option>
      <option>slide</option>
      <option>fray</option>
      <option>wicked</option>
      <option>sculpt</option>
      <option>long</option>                      
    </select>
  </div>
  <div>
    Corner orientation:
    <select id="chooseCornerOrientation" class="select select-xs w-full">
      <option></option>
      <option>top</option>
      <option>bottom</option>
    </select>
  </div>
  <div>
    Radius(px):<input id="cornerParamRadius" class="input input-sm w-full" type="text"> 
  </div>
  <div>
    Container BG:<input id="cornerParamBg" readonly="readonly" data-coloris class="input input-sm w-full" type="text">
  </div>
  <div class="">
    <input id="cornerParamButton" class="btn btn-xs btn-secondary w-full" type="submit" value="Apply">
  </div>
</div>