<?php
/**
* IDE21 Content Management System
*
* @category   Layouts
* @package    IDE21
*  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
*
*  This file is part of IDE21.
*
*  IDE21 is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
*
*
*
*/
?>

<div id="penPointer" class="object-buttons help absolute hidden z-[99999] p-2 bg-red-400 border-2 border-white text-white rounded-full" title="<?php echo $this->translate->_("Click to edit currently selected object in WYSIWYG");?>">
  <svg class="w-4 h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
    <path d="M21.731 2.269a2.625 2.625 0 0 0-3.712 0l-1.157 1.157 3.712 3.712 1.157-1.157a2.625 2.625 0 0 0 0-3.712ZM19.513 8.199l-3.712-3.712-12.15 12.15a5.25 5.25 0 0 0-1.32 2.214l-.8 2.685a.75.75 0 0 0 .933.933l2.685-.8a5.25 5.25 0 0 0 2.214-1.32L19.513 8.2Z" />
  </svg>
</div>
<div id="downPointer"></div>
<div id="movePointer" class="object-buttons help absolute hidden z-[99999] p-2 bg-red-400 border-2 border-white text-white rounded-full" title="<?php echo $this->translate->_("Click to MARK currently selected object for moving outside its parent");?>">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-4">
    <path fill-rule="evenodd" d="M15.22 6.268a.75.75 0 0 1 .968-.431l5.942 2.28a.75.75 0 0 1 .431.97l-2.28 5.94a.75.75 0 1 1-1.4-.537l1.63-4.251-1.086.484a11.2 11.2 0 0 0-5.45 5.173.75.75 0 0 1-1.199.19L9 12.312l-6.22 6.22a.75.75 0 0 1-1.06-1.061l6.75-6.75a.75.75 0 0 1 1.06 0l3.606 3.606a12.695 12.695 0 0 1 5.68-4.974l1.086-.483-4.251-1.632a.75.75 0 0 1-.432-.97Z" clip-rule="evenodd" />
  </svg>
</div>
<div id="dropPointer" class="object-buttons help absolute hidden z-[99999] p-2 bg-red-400 border-2 border-white text-white rounded-full" title="<?php echo $this->translate->_("Click to move the previously MARKED object into the currently selected object which will become its new parent");?>">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-4">
    <path fill-rule="evenodd" d="M1.72 5.47a.75.75 0 0 1 1.06 0L9 11.69l3.756-3.756a.75.75 0 0 1 .985-.066 12.698 12.698 0 0 1 4.575 6.832l.308 1.149 2.277-3.943a.75.75 0 1 1 1.299.75l-3.182 5.51a.75.75 0 0 1-1.025.275l-5.511-3.181a.75.75 0 0 1 .75-1.3l3.943 2.277-.308-1.149a11.194 11.194 0 0 0-3.528-5.617l-3.809 3.81a.75.75 0 0 1-1.06 0L1.72 6.53a.75.75 0 0 1 0-1.061Z" clip-rule="evenodd" />
  </svg>
</div>
<div id="moveUpPointer" class="object-buttons help absolute hidden z-[99999] p-2 bg-red-400 border-2 border-white text-white rounded-full" title="<?php echo $this->translate->_("Click to move currently selected object within the parent UP");?>">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-4">
    <path fill-rule="evenodd" d="M11.47 2.47a.75.75 0 0 1 1.06 0l3.75 3.75a.75.75 0 0 1-1.06 1.06l-2.47-2.47V21a.75.75 0 0 1-1.5 0V4.81L8.78 7.28a.75.75 0 0 1-1.06-1.06l3.75-3.75Z" clip-rule="evenodd" />
  </svg>
</div>
<div id="moveDownPointer" class="object-buttons help absolute hidden z-[99999] p-2 bg-red-400 border-2 border-white text-white rounded-full" title="<?php echo $this->translate->_("Click to move currently selected object within the parent DOWN");?>">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-4">
    <path fill-rule="evenodd" d="M12 2.25a.75.75 0 0 1 .75.75v16.19l2.47-2.47a.75.75 0 1 1 1.06 1.06l-3.75 3.75a.75.75 0 0 1-1.06 0l-3.75-3.75a.75.75 0 1 1 1.06-1.06l2.47 2.47V3a.75.75 0 0 1 .75-.75Z" clip-rule="evenodd" />
  </svg>
</div>


<div id="tooltip" class="text-balance" style="display:none"></div>
<div id="adminAjaxLoader"><div
  class="inline-block h-8 w-8 animate-spin rounded-full border-4 border-solid border-current border-e-transparent align-[-0.125em] text-surface motion-reduce:animate-[spin_1.5s_linear_infinite] dark:text-white"
  role="status">
  <span
    class="!absolute !-m-px !h-px !w-px !overflow-hidden !whitespace-nowrap !border-0 !p-0 ![clip:rect(0,0,0,0)]"
    >Loading...</span
  >
</div></div>

<!--form for saving and updating page-->
<form id="pageCode" name="pageCode" data-objid="" style="display:none" action="<?php echo $this->host;?>page/save" method="post">
  <input name="pageTitleC" id="pageTitleC" class="input w-full" value="" />
  <input name="pageImageC" id="pageImageC" class="input w-full" value="" />
  <textarea id="pageCodeHtml" name="pageCodeHtml"></textarea>
  <textarea id="pageCSSC" name="pageCSSC"></textarea>
  <textarea id="pageJSC" name="pageJSC"></textarea>
  <textarea id="pageDESC" name="pageDESC"></textarea>
  <textarea id="pageKEYWORDS" name="pageKEYWORDS"></textarea>
  <input id="pageCategoryC" name="pageCategoryC" type="text" value="" />
</form>

<!--form for saving and updating template-->
<form id="templateCode" name="templateCode" data-objid="" style="display:none" action="<?php echo $this->host;?>page/save-as-template" method="post">
  <input name="templateTitleC" id="templateTitleC" value="" />
  <input name="templateBodyBgC" id="templateBodyBgC" value="" />
  <input name="templateDefaultC" id="templateDefaultC" value="" />
  <textarea id="templateCodeHtml" name="templateCodeHtml"></textarea>
</form>

<div class="grid grid-cols-12 relative">
  <div id="containerRadnePovrsine" data-simplebar  data-scrollbar-min-size="15"  class="col-span-12 md:col-span-8 lg:col-span-9">
    <div id="droppable" class="w-full overflow-auto">
    </div>
    <div id="droppable_" class="w-full overflow-auto">
    </div>
  </div>

  <div data-theme="nord" id="toggleProperties"  class="help fixed -right-2 top-2/4 z-[999999] bg-neutral hover:bg-accent z-[999999] border-2 border-primary cursor-pointer btn btn-sm md:btn-xs btn-ghost btn-circle text-white" title="<?php echo $this->translate->_("Click to toggle properties box");?>">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-4 rotate-90">
        <path fill-rule="evenodd" d="M11.47 7.72a.75.75 0 0 1 1.06 0l7.5 7.5a.75.75 0 1 1-1.06 1.06L12 9.31l-6.97 6.97a.75.75 0 0 1-1.06-1.06l7.5-7.5Z" clip-rule="evenodd"></path>
      </svg>
  </div>
  <div data-theme="nord" id="contProperties" class="absolute md:relative col-span-4 lg:col-span-3 w-full h-dvh top-0 right-0 md:pb-12 ease-in duration-400">
    <div id="propertiesLeft">
      <h2><?php echo $this->translate->_("Welcome to NeT.Objects!");?></h2>
      <p><?php echo $this->translate->_("Drag & Drop items from toolbox to create objects on the page");?></p>
    </div>

    <div id="properties" class="w-full h-dvh overflow-auto">
      <div id="rotate" class="ui-tabs pt-0 pb-44 md:pb-16 px-0 bg-primary text-primary-content shadow-lg rounded-none">
        <ul id="tabs-navigation" class="tabs tabs-boxed ui-tabs-nav fixed grid grid-cols-3 bottom-0 md:sticky md:top-0 md:bottom-auto w-full h-28 bg-none bg-neutral border-0 rounded-none">
          <li role="tab" class="help tab ui-tab-button  row-start-auto" description="<?php echo $this->translate->_("Contains properties of page and objects");?>"><a href="#fragment-1" id="poA" title="Object properties on a Page or a  Template"><span><?php echo $this->translate->_("Objects");?></span></a></li>
          <li role="tab"  class="help tab ui-tab-button  row-start-auto" description="<?php echo $this->translate->_("Contains Menu management");?>"><a href="#fragment-2" id="MenuA"><span><?php echo $this->translate->_("Menus");?></span></a></li>
          <li role="tab"  class="help tab ui-tab-button  row-start-auto" description="<?php echo $this->translate->_("Contains Categories management");?>"><a href="#fragment-3" id="CatA"><span><?php echo $this->translate->_("Categories");?></span></a></li>
          <li role="tab"  class="help tab ui-tab-button  row-start-auto" description="<?php echo $this->translate->_("Installed and enabled languages on the site");?>"><a href="#fragment-4" id="LangA"><span><?php echo $this->translate->_("Languages");?></span></a></li>
          <li role="tab"  class="help tab ui-tab-button  row-start-auto" description="<?php echo $this->translate->_("Installed and enabled modules on the site");?>"><a href="#fragment-5" id="ModA"><span><?php echo $this->translate->_("Modules");?></span></a></li>
          <li role="tab"  class="help tab ui-tab-button  row-start-auto" description="<?php echo $this->translate->_("Galleries and Images on the site");?>"><a href="#fragment-6" id="ImagesA"><span><?php echo $this->translate->_("Images");?></span></a></li>
          <li role="tab"  class="help tab ui-tab-button  row-start-auto" description="<?php echo $this->translate->_("CSS code - every administrator's code is compiled together in the main css file");?>"><a href="#fragment-7" id="CssA"><span>CSS</span></a></li>
          <li role="tab"  class="help tab ui-tab-button  row-start-auto" description="<?php echo $this->translate->_("JavaScript code - every administrator's code is compiled together in the main javascript file");?>"><a href="#fragment-8" id="JsA"><span>JS</span></a></li>
          <li role="tab"  class="help tab ui-tab-button  row-start-auto" description="<?php echo $this->translate->_("Site Settings");?>"><a href="#fragment-9" id="SettingsA"><span><?php echo $this->translate->_("Settings");?></span></a></li>

        </ul>
        <div id="fragment-1" style="padding: 1em 1.4em;">
          <form id="objProperties" name="objProperties" data-objid="" action="<?php echo $this->host;?>save" method="post">

            <div class="grid">  
              <div class="grid gap-2">
                <div class="" >
                  <?php echo $this->langChooserAdmin;?>
                </div>

                <div class="">
                  <div style="display:none"><?php echo $this->translate->_("Container");?><input id="objContainer" type="checkbox" /></div>
                <?php echo $this->translate->_("Objects on this page");?>:
                <select id="objList" size="8" class="help select select-sm md:select-xs min-h-32 text-primary-content w-full p-1 mb-2" title="<?php echo $this->translate->_("This is the list of all objects in this page/template");?><?php echo $this->translate->_(". Select the object to work on it."); ?>">
                </select>
                </div>

                <a href="" id="clearPage" class="navLinks a_clear noAjaxEvent btn btn-error btn-sm md:btn-xs mb-2" title="<?php echo $this->translate->_("Click to erase all objects");?>"><?php echo $this->translate->_("Clear");?></a>
                <a href="" id="toggleVisibilityRowAnchor" class="navLinks a_content noAjaxEvent btn btn-secondary btn-sm md:btn-xs mb-2 " title="<?php echo $this->translate->_("Toggle visibility for style, tinymce and meta");?>"><?php echo $this->translate->_("Object Editors");?></a>

              </div>
              <div id="toggleVisibilityRow" class="grid gap-4" style="display:none">

                <div class="flex flex-col my-2">
                  <?php echo $this->translate->_("Style for this object");?>:
                  <textarea id="objPropertiesCSS" name="objPropertiesCSS" class="help textarea" title="<?php echo $this->translate->_("Style for this object");?>"></textarea>
                  <a href="" id="applyStyle" class="navLinks noAjaxEvent btn btn-secondary btn-sm md:btn-xs mb-2 help" title="<?php echo $this->translate->_("Click to apply this HTML to the selected object");?>">Apply</a>
                </div>
                <!-- tinyMCE should be replaced -->
                <div class="flex flex-col h-52 my-2 hidden">
                  <textarea id="objPropertiesHtmlTiny" name="objPropertiesHtmlTiny" style="height:100px;">
                  </textarea>
                </div>
                <div id="selected-object-html-wrapper" class="flex flex-col min-h-32 bg-primary">
                  <div class="grid grid-cols-4 ">
                    <div class="col-span-3"><?php echo $this->translate->_("HTML of this object");?>:</div>
                    <div class="justify-self-end mr-1 mb-1">
                      <a href="#" class="help fsbutton w-8" id="fsbuttonHtml">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-4 h-4">
                          <path fill-rule="evenodd" d="M15 3.75a.75.75 0 0 1 .75-.75h4.5a.75.75 0 0 1 .75.75v4.5a.75.75 0 0 1-1.5 0V5.56l-3.97 3.97a.75.75 0 1 1-1.06-1.06l3.97-3.97h-2.69a.75.75 0 0 1-.75-.75Zm-12 0A.75.75 0 0 1 3.75 3h4.5a.75.75 0 0 1 0 1.5H5.56l3.97 3.97a.75.75 0 0 1-1.06 1.06L4.5 5.56v2.69a.75.75 0 0 1-1.5 0v-4.5Zm11.47 11.78a.75.75 0 1 1 1.06-1.06l3.97 3.97v-2.69a.75.75 0 0 1 1.5 0v4.5a.75.75 0 0 1-.75.75h-4.5a.75.75 0 0 1 0-1.5h2.69l-3.97-3.97Zm-4.94-1.06a.75.75 0 0 1 0 1.06L5.56 19.5h2.69a.75.75 0 0 1 0 1.5h-4.5a.75.75 0 0 1-.75-.75v-4.5a.75.75 0 0 1 1.5 0v2.69l3.97-3.97a.75.75 0 0 1 1.06 0Z" clip-rule="evenodd"></path>
                        </svg>
                      </a>
                    </div>
                  </div>
                  <textarea id="objPropertiesHtmlSelected" name="objPropertiesHtmlSelected" class="hidden textarea min-h-32"></textarea>
                  <div id="objectHTML-ace" class="w-full h-full min-h-32"></div>
                </div>

                <div class="">
                  <div id="descKeyDiv" class="">
                    <div class="flex flex-col my-2">
                      DESCRIPTION:
                      <textarea id="pageDescription" name="pageDescription" class="help textarea h-40" title="<?php echo $this->translate->_("Here write the description for your page, which will make it Search Engine Optimized...");?>">
                        <?php echo $this->description;?>
                      </textarea>
                    </div>

                    <div class="flex flex-col my-2">
                      KEYWORDS:
                      <textarea id="pageKeywords" name="pageKeywords"class="help textarea" title="<?php echo $this->translate->_("Here write the keywords for your page, which will make it Search Engine Optimized...");?>">
                        <?php echo $this->keywords;?>
                      </textarea>
                    </div>
                  </div>
                </div>
              </div>

              <div class="grid grid-cols-4 item-strech gap-2 my-2">
                <div class="font-black col-span-1" ><?php echo $this->translate->_("Page ID");?>:</div>
                <div id="pgID" class="col-span-3"><?php echo $this->pageId;?>
                
              </div>

              <div class="font-black col-span-1"><?php echo $this->translate->_("ObjectID");?>:</div>
              <div id="objIDshow" class="col-span-3"></div>
            </div>


            <div class="grid place-items-strech gap-4" >
              <div class="grid gap-y-2 content-start">
                <div class="grid mt-1 gap-y-2 h-24">
                  <div class="creatorDiv grid grid-cols-2 items-strech"><span class="cl"><?php echo $this->translate->_("ID Assistant");?></span><span><input id="tttoggle" type="checkbox"  class="checkbox-sm checkbox float-right" checked="false" /></span></div>
                  <div class="creatorDiv grid grid-cols-2 items-strech"><span class="cl"><?php echo $this->translate->_("Show hidden");?>:</span><span><input id="showFooterCheck" name="showFooterCheck" type="checkbox" class="checkbox-sm checkbox float-right" /></span></div>
                  <div class="creatorDiv grid grid-cols-4 items-strech"><span class="cl col-span-3"><?php echo $this->translate->_("Shadow");?></span><span> <a href="" class="navLinks help a_params noAjaxEvent currentTitle" id="aParamShadow" title="<?php echo $this->translate->_("Click to set shadow params");?>">
                    <svg class="w-4 h-4 fill-current bg-secondary text-white rounded-full inline-block" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                      <path d="M16.5 6a3 3 0 0 0-3-3H6a3 3 0 0 0-3 3v7.5a3 3 0 0 0 3 3v-6A4.5 4.5 0 0 1 10.5 6h6Z" />
                      <path d="M18 7.5a3 3 0 0 1 3 3V18a3 3 0 0 1-3 3h-7.5a3 3 0 0 1-3-3v-7.5a3 3 0 0 1 3-3H18Z" />
                    </svg>
                    <div class="hidden">Shadow</div>
                  </a><input id="shadowCheck" type="checkbox" class="checkbox-sm checkbox float-right"  /></span></div>
                  <div class="creatorDiv grid grid-cols-4 items-strech"><span class="cl col-span-3"><?php echo $this->translate->_("Corner");?></span><span> <a href="" class="navLinks help a_params noAjaxEvent currentTitle content-center h-6 inline-block" id="aParamCorner" title="<?php echo $this->translate->_("Click to set corner params");?>">
                    <svg class="w-4 h-4 fill-current text-white rounded" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" >
                      <path d="M6 3a3 3 0 0 0-3 3v1.5a.75.75 0 0 0 1.5 0V6A1.5 1.5 0 0 1 6 4.5h1.5a.75.75 0 0 0 0-1.5H6ZM16.5 3a.75.75 0 0 0 0 1.5H18A1.5 1.5 0 0 1 19.5 6v1.5a.75.75 0 0 0 1.5 0V6a3 3 0 0 0-3-3h-1.5ZM12 8.25a3.75 3.75 0 1 0 0 7.5 3.75 3.75 0 0 0 0-7.5ZM4.5 16.5a.75.75 0 0 0-1.5 0V18a3 3 0 0 0 3 3h1.5a.75.75 0 0 0 0-1.5H6A1.5 1.5 0 0 1 4.5 18v-1.5ZM21 16.5a.75.75 0 0 0-1.5 0V18a1.5 1.5 0 0 1-1.5 1.5h-1.5a.75.75 0 0 0 0 1.5H18a3 3 0 0 0 3-3v-1.5Z" />
                    </svg>
                    <div class="hidden">Corner</div>
                  </a><input id="cornerCheck" type="checkbox" class="checkbox-sm checkbox float-right"  /></span></div>
                </div>

                <div id="fontCont" style="display:none;">
                  Font:
                  <a id="fontBigger" style="width:30px;height:30px;"><img src="<?php echo $this->host;?>images/interface/fontPlus.png" /></a><a id="fontSmaller" style="width:30px;height:30px;"><img src="<?php echo $this->host;?>images/interface/fontMinus.png" /></a>
                </div>

                <div class="mt-4">
                  <?php echo $this->translate->_("Type");?>:

                  <select id="objType" class="help select  select-sm md:select-xs mt-1 w-full"  description="<?php echo $this->translate->_("Choose the type of the selected object, after you do it, follow the instructions");?>">
                    <option class="Text" >Text</option>
                    <option class="Menu" >Menu</option>
                    <option class="category" >Category</option>
                    <option class="Image">Image</option>
                    <option class="title">Page Title</option>
                    <option class="pageinfo">Page Info</option>
                    <option class="searchform">Search Form</option>
                    <option class="languageform">Language Form</option>
                    <option class="contactform">Contact Form</option>
                    <option class="footer">Footer</option>
                    <option class="contentarea">Content area</option>
                    <option class="loginarea">Login area</option>
                  </select>
                </div>

                <!--Disable theme changer for now, it should be replaced with Daisyui themes changer<div class="mt-4">
                  <?php echo $this->translate->_("Theme");?>:
                  <select id="objTheme" class="help select  select-sm md:select-xs mt-1 w-full" description="<?php echo $this->translate->_("Choose the theme for the selected object");?>">
                    <option value="no">None</option>
                    <option value="silver">Silver</option>
                    <option value="green">Green</option>
                    <option value="red">Red</option>
                    <option value="blue">Blue</option>
                    <option value="white">White</option>
                    <option value="black">Black</option>
                  </select>
                </div>-->
              </div>

              <div class="grid grid-cols-4 h-96 items-strech justify-items-end">
                <span class="cl col-span-3 justify-self-start"><?php echo $this->translate->_("Width");?>:</span><span><input id="objPropertiesWidth" name="objPropertiesWidth"class="input w-16 max-h-5 p-0" type="text" value="" /></span>
                <span class="cl col-span-3 justify-self-start"><?php echo $this->translate->_("Height");?>:</span><span><input id="objPropertiesHeight" name="objPropertiesHeight"class="input w-16 max-h-5 p-0" type="text" value="" /></span>
                <span class="cl col-span-3 justify-self-start"><?php echo $this->translate->_("Border");?>:</span><span><input id="objPropertiesBorder" name="objPropertiesBorder"class="input w-16 max-h-5 p-0" type="text" value="" /></span>

                <span class="cl col-span-3 justify-self-start">PosX:</span><span><input id="objPropertiesX" name="objPropertiesX"class="input w-16 max-h-5 p-0" type="text" value="" /></span>
                <span class="cl col-span-3 justify-self-start">PosY:</span><span><input id="objPropertiesY" name="objPropertiesY"class="input w-16 max-h-5 p-0" type="text" value="" /></span>
                <span class="cl col-span-3 justify-self-start">Z-Index:</span><span><input id="objPropertiesZ" name="objPropertiesZ"class="input w-16 max-h-5 p-0" type="text" value="" /></span>

                <span class="cl col-span-3 justify-self-start">BgColor:</span><span><input id="objPropertiesBackground" name="objPropertiesBackground"class="input w-16 max-h-5 p-0" type="text" value="" data-coloris /></span>
                <span class="cl col-span-3 justify-self-start">FontColor:</span><span><input id="objPropertiesFontColor" name="objPropertiesFontColor"class="input w-16 max-h-5 p-0" type="text" value="" data-coloris /></span>

                <span class="cl col-span-3 justify-self-start">BgImage:</span><span><input id="objPropertiesBackgroundImage" name="objPropertiesBackgroundImage"class="input w-16 max-h-5 p-0" type="text" value="" /></span>
                <span class="cl col-span-3 justify-self-start">Position:</span><span>
                  <select name="selected-object-position" id="selected-object-position" class="help select select-xs w-16" title="Set the position of the selected object." size="1">
                      <option value="static" selected="selected">Static</option>
                      <option value="relative">Relative</option>
                      <option value="fixed">Fixed</option>
                      <option value="absolute">Absolute</option>
                      <option value="sticky">Sticky</option>
                  </select>
                </span>

                <span class="w-full col-span-4 justify-self-start mt-2">
                  <div class="grid grid-cols-6 justify-items-center">
                    <div id="toggleFontWeight" class="help cursor-pointer btn btn-sm btn-ghost btn-circle text-white" title="Click to toggle font-weight">
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-4 h-4">
                        <path fill-rule="evenodd" d="M5.246 3.744a.75.75 0 0 1 .75-.75h7.125a4.875 4.875 0 0 1 3.346 8.422 5.25 5.25 0 0 1-2.97 9.58h-7.5a.75.75 0 0 1-.75-.75V3.744Zm7.125 6.75a2.625 2.625 0 0 0 0-5.25H8.246v5.25h4.125Zm-4.125 2.251v6h4.5a3 3 0 0 0 0-6h-4.5Z" clip-rule="evenodd" />
                      </svg>
                    </div>

                    <div id="toggleFontStyle" class="help cursor-pointer btn btn-sm btn-ghost btn-circle text-white" title="Click to toggle font-style">
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-4 h-4">
                        <path fill-rule="evenodd" d="M10.497 3.744a.75.75 0 0 1 .75-.75h7.5a.75.75 0 0 1 0 1.5h-3.275l-5.357 15.002h2.632a.75.75 0 1 1 0 1.5h-7.5a.75.75 0 1 1 0-1.5h3.275l5.357-15.002h-2.632a.75.75 0 0 1-.75-.75Z" clip-rule="evenodd" />
                      </svg>
                    </div>

                    <div id="toggleUnderline" class="help cursor-pointer btn btn-sm btn-ghost btn-circle text-white" title="Click to toggle underline">
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-4 h-4">
                        <path fill-rule="evenodd" d="M5.995 2.994a.75.75 0 0 1 .75.75v7.5a5.25 5.25 0 1 0 10.5 0v-7.5a.75.75 0 0 1 1.5 0v7.5a6.75 6.75 0 1 1-13.5 0v-7.5a.75.75 0 0 1 .75-.75Zm-3 17.252a.75.75 0 0 1 .75-.75h16.5a.75.75 0 0 1 0 1.5h-16.5a.75.75 0 0 1-.75-.75Z" clip-rule="evenodd" />
                      </svg>
                    </div>
                    <div id="toggleTextCenter" class="help cursor-pointer btn btn-sm btn-ghost btn-circle text-white" title="Click to toggle underline">
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-4">
                        <path fill-rule="evenodd" d="M3 6.75A.75.75 0 0 1 3.75 6h16.5a.75.75 0 0 1 0 1.5H3.75A.75.75 0 0 1 3 6.75ZM3 12a.75.75 0 0 1 .75-.75h16.5a.75.75 0 0 1 0 1.5H3.75A.75.75 0 0 1 3 12Zm0 5.25a.75.75 0 0 1 .75-.75h16.5a.75.75 0 0 1 0 1.5H3.75a.75.75 0 0 1-.75-.75Z" clip-rule="evenodd" />
                      </svg>
                    </div>
                    <div id="toggleTextLeft" class="help cursor-pointer btn btn-sm btn-ghost btn-circle text-white" title="Click to toggle underline">
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-4">
                        <path fill-rule="evenodd" d="M3 6.75A.75.75 0 0 1 3.75 6h16.5a.75.75 0 0 1 0 1.5H3.75A.75.75 0 0 1 3 6.75ZM3 12a.75.75 0 0 1 .75-.75h16.5a.75.75 0 0 1 0 1.5H3.75A.75.75 0 0 1 3 12Zm0 5.25a.75.75 0 0 1 .75-.75H12a.75.75 0 0 1 0 1.5H3.75a.75.75 0 0 1-.75-.75Z" clip-rule="evenodd" />
                      </svg>
                    </div>
                    <div id="toggleTextRight" class="help cursor-pointer btn btn-sm btn-ghost btn-circle text-white" title="Click to toggle underline">
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-4">
                        <path fill-rule="evenodd" d="M3 6.75A.75.75 0 0 1 3.75 6h16.5a.75.75 0 0 1 0 1.5H3.75A.75.75 0 0 1 3 6.75ZM3 12a.75.75 0 0 1 .75-.75h16.5a.75.75 0 0 1 0 1.5H3.75A.75.75 0 0 1 3 12Zm8.25 5.25a.75.75 0 0 1 .75-.75h8.25a.75.75 0 0 1 0 1.5H12a.75.75 0 0 1-.75-.75Z" clip-rule="evenodd" />
                      </svg>
                    </div>
                  </div>
                </span>

                <!-- classes are to be handled through former ID assistant -->
                <div id="id-assistant-container"></div>
                <div class="hidden"><span class="cl col-span-4 justify-self-start">class:</span><span class="col-span-4 w-full"><input id="objPropertiesClass" name="objPropertiesClass"class="input w-full max-h-8 p-0" type="text" value="" /></span></div>
                <!-- classes are to be handled through former ID assistant -->

              </div>
              <div class="grid gap-2">
                <a href="" id="newPage" class="navLinks a_new" style="display:none" title="<?php echo $this->translate->_("Click to create new page");?>"><?php echo $this->translate->_("New Page");?></a>
                <a href="<?php echo $this->host;?>creator/manage-all-pages?height=450&width=900" id="manageAllPages" class="thickbox btn btn-secondary btn-sm mb-4" title="<?php echo $this->translate->_("Manage All Pages");?>"><b><?php echo $this->translate->_("Manage All Pages");?></b></a>
                <a href="" id="openPage" class="navLinks a_open btn btn-secondary btn-sm md:btn-xs mb-2" title="<?php echo $this->translate->_("Click to open existing page");?>"><?php echo $this->translate->_("Open Page");?></a>
                <a id="previewButton" class="a_preview help btn btn-secondary btn-sm md:btn-xs mb-2" target="_blank" href="" title="<?php echo $this->translate->_("Click this to go to the page and see how it looks!");?>"><?php echo $this->translate->_("View Page");?></a>
                <div class="page-title"><?php echo $this->translate->_("Page Title");?>:<input id="pageTitle" class="input input-sm w-full" type="text" name="pageTitle" value="Page <?php echo $this->pageId;?>" /></div>
                <a href="#" class="navLinks a_redraw noAjaxEvent btn btn-secondary btn-sm md:btn-xs mb-2" id="redraw" style="display:none;"><?php echo $this->translate->_("Redraw");?></a>
                <div id="pageEditing" class="grid gap-2">
                  <a href="" id="saveThisPage" class="navLinks a_save btn btn-secondary btn-sm md:btn-xs mb-2" title="<?php echo $this->translate->_("Click to save work on this page");?>"><?php echo $this->translate->_("Save Page");?></a>
                  <a href="" id="savePageNew" class="navLinks a_save_new btn btn-secondary btn-sm md:btn-xs mb-2" title="<?php echo $this->translate->_("Click to save this work as a new page");?>"><?php echo $this->translate->_("Save As New Page");?></a>

                  <div class="w-full">

                    <div class="creatorDiv inline-flex gap-2 items-center w-full"><input id="allLangCheck" type="checkbox" class="checkbox-sm checkbox" /><?php echo $this->translate->_("Apply to all languages");?></div>

                    <div id="restrictiveDiv" class="inline-flex gap-2 items-center w-full"><input id="restrictiveCB" type="checkbox" class="checkbox-sm checkbox"  /><?php echo $this->translate->_("Restrictive");?>
                    <a href="" style="display:none" id="openPagePermisions" class="navLinks a_access btn btn-xs btn-secondary" title="<?php echo $this->translate->_("Click to set permissions for this page");?>"><?php echo $this->translate->_("Permissions");?></a>
                    <div id="allowedRolesDiv" class="w-full p-2"></div>
                  </div>

                  <div id="boundDiv" class="inline-flex gap-2 items-center w-full">
                    <input id="boundCB" type="checkbox" checked="checked" class="checkbox-sm checkbox" /><?php echo $this->translate->_("Relative to Content Area");?>
                  </div>

                </div>
                <a href="" id="deletePage" class="navLinks a_delete btn btn-error btn-sm mt-2 text-content-secondary p-2 max-h-2" title="<?php echo $this->translate->_("Click to delete this page");?>"><?php echo $this->translate->_("Delete This Page");?></a>

                <div style="display:none;" class="font-black" ><?php echo $this->translate->_("Template ID");?>:</div> <div id="templateID" style="display:none;"><?php echo $this->templateId;?></div>
                
                <div id="templateChangerDiv" class="card w-full mt-2"><?php echo $this->changeTemplate;?></div>


                <div class="page-image"><?php echo $this->translate->_("Page Image");?>:<input id="pageImage" class="input input-sm w-full" type="text" name="pageImage" value="<?php echo $this->pageImage;?>" /></div>

              </div>

              <div id="templateEditing" class="grid gap-y-2" style="display:none;">
                <div class="grid grid-cols-2">
                  <div class="font-black" >
                    <?php echo $this->translate->_("Template ID");?>:</div> 
                    <div id="templateIDediting" class=""><?php echo $this->templateIdEdit;?></div>
                  </div>
                  <div>
                    <?php echo $this->translate->_("Template name");?>:
                    <input id="templateTitle" type="text" name="templateTitle" value="<?php echo $this->templateName;?>" class="input input-bordered input-sm w-full" />
                  </div>

                  <a href="" id="applyTemplate" class="navLinks a_edit btn btn-secondary btn-sm md:btn-xs" title="<?php echo $this->translate->_("Click to edit existing template");?>"><?php echo $this->translate->_("Edit template");?></a>
                  <a href="" id="saveThisTemplate" class="navLinks a_save btn btn-secondary btn-sm md:btn-xs" title="<?php echo $this->translate->_("Click to save work on this template");?>"><?php echo $this->translate->_("Save Template");?></a>
                  <a href="" id="saveAsTemplate" class="navLinks a_save_new btn btn-secondary btn-sm md:btn-xs"  title="<?php echo $this->translate->_("Click to save this work as template");?>"><?php echo $this->translate->_("Save As New Template");?></a>
                  <div class="creatorDiv inline-flex gap-2 items-center"><input id="allLangCheckTemplate" class="checkbox-sm checkbox" type="checkbox" /><?php echo $this->translate->_("Apply to all languages");?></div>
                  <div id="DefaultTemplateChangerDiv" class="inline-flex gap-2 items-center"><input id="templateDefaultCB" class="checkbox-sm checkbox" type="checkbox" name="templateDefaultCB" /><?php echo $this->translate->_("Default Template");?></div>

                  <a href="" id="exportTemplate" class="navLinks a_edit btn btn-secondary btn-sm md:btn-xs btn-disabled" title="<?php echo $this->translate->_("Click to export this template for use on another installation.");?>"><?php echo $this->translate->_("Export Template");?></a>
                  <a href="" id="installTemplate" class="navLinks a_save btn btn-secondary btn-sm md:btn-xs btn-disabled" title="<?php echo $this->translate->_("Click to install exported template");?>"><?php echo $this->translate->_("Install Template");?></a>
                  <a href="" id="deleteTemplate" class="navLinks a_delete btn btn-sm btn-secondary btn-error" title="<?php echo $this->translate->_("Click to delete this template");?>"><?php echo $this->translate->_("Delete This Template");?></a>
                </div>
              </div>

              <div class="grid gap-2">
                <div id="assignPageToCategory">
                  <?php echo $this->formAssignPageToCategory;?>
                </div>

                <div id="assignPageToMenu">
                  <?php echo $this->formAssignPageToMenu;?>
                </div>
                <div style="display:none;">
                  <div>BodyW:<input id="bodyWidth" name="bodyWidth" type="text" value="" /></div>
                  <div>BodyH:<input id="bodyHeight" name="bodyHeight" type="text" value="" /></div>

                </div>
                BodyBg:<input id="template_bodyBg" name="template_bodyBg" type="text" value="" class="input input-sm w-full mb-2" />

                <a id="emptyCacheButton" class="navLinks a_emptyCache help btn btn-secondary btn-sm md:btn-xs mb-2" href="" title="<?php echo $this->translate->_("Click this to empty the cache if you have made changes that require cache to be cleaned!");?>"><?php echo $this->translate->_("Empty Cache");?> </a>

                <!--<a id="backupSiteButton" class="navLinks a_backup help btn btn-secondary btn-sm md:btn-xs mb-2" href="" title="<?php echo $this->translate->_("Click here to have backup of the site in a folder that is created for that purpose.If system command is disabled then it must be done through phpMyAdmin...");?>"><?php echo $this->translate->_("Backup Site");?> </a> HIDE UNTIL FIXED -->

                <!--<a id="generateCacheButton" class="navLinks a_generateCache" style="display:block" href="" >Generate Cache </a>-->
              </div>

            </div>
          </div><!-- end container div holding Page/Object-->
        </form>

      </div>

      <!--MENUS-->

      <div id="fragment-2">
        <div id="menuFormContainer" class="grid gap-4 min-h-96">
          <div id="menuShow" class="grid gap-2 content-start">

            <div class="inline-flex items-center gap-2">
              <?php echo $this->translate->_("Put in this object");?> <input id="putInThis" class="checkbox-sm checkbox" type="checkbox" />
            </div>

            <div class="grid items-center gap-2">
              <?php echo $this->translate->_("Display Type");?>:
              <form id="menuDisplayType" class="inline-flex items-center gap-1">
                <input class="radio-sm" type="radio" name="displaytype" value="" checked="checked">Horizontal
                <input class="radio-sm" type="radio" name="displaytype" value=":vertical">Vertical
                <input class="radio-sm" type="radio" name="displaytype" value=":tree">Tree
                <!-- SLIDE MENU DISPLAY DISABLED FOR NOW, TODO: MAKE IT WORK WITH DAISYUI OR SOMETHING ELSE -->
                <!-- <input class="radio-sm" type="radio" name="displaytype" value=":slide">Slide -->
              </form>
            </div>

            <div>
              <?php echo $this->formChooseMenu;?>
              <div class="flex gap-2 mt-2"><span><?php echo $this->translate->_("Selected menu ID:");?></span><span id="chosen-menu-id"></span></div>
            </div>
            <div id="addMenuLinkDiv" class="grid gap-2">
              <a id="addMenuLink" href="menu/add-menu" class="navLinks a_add btn btn-sm md:btn-xs" title="<?php echo $this->translate->_("Click to create new menu");?>"><?php echo $this->translate->_("Add a menu");?></a>
              <a id="delMenuLink" href="menu/del-menu" class="navLinks a_delete btn btn-sm md:btn-xs btn-error" title="<?php echo $this->translate->_("Click to delete menu");?>"><?php echo $this->translate->_("Delete menu");?></a>
              <a id="addMenuItemLink" href="menu/add-menu-item" class="navLinks a_add btn btn-sm md:btn-xs" title="<?php echo $this->translate->_("Click to add new menu item to this menu");?>"><?php echo $this->translate->_("Add a menu item");?></a>

            </div>

          </div>
          <div id="menuSelected" class="grid gap-2 content-start bg-neutral-content rounded min-h-20"></div>
          <div id="menuSelectedForm" class="grid gap-2 content-start">
            <a id="editMenuItem" style="display:none">Edit</a>
            <a id="deleteMenuItem" class="a_delete btn btn-sm md:btn-xs btn-error" style="display:none" title="<?php echo $this->translate->_("Click to delete this menu item");?>"><?php echo $this->translate->_("Delete this item");?> </a>
            <div id="menuItemForm"></div>
          </div>

        </div>

      </div>

      <!--Categories-->

      <div id="fragment-3">
        <div id="categoryFormContainer" class="grid gap-4" >
          <div class="grid gap-2 content-start">
            <div>
              <?php echo $this->translate->_("Put in this object");?> <input id="putCategoryInThis" class="checkbox-sm checkbox" type="checkbox" />
            </div>

            <div id="categoryShow">
              <?php echo $this->formChooseCategory;?>
            </div>

            <div id="addCategoryLinkDiv" class="grid gap-2">
              <a id="addCategoryLink" href="category/add-category" class="navLinks a_add btn btn-sm md:btn-xs" title="<?php echo $this->translate->_("Click to create new category");?>"><?php echo $this->translate->_("Add a category");?></a>
              <a id="delCategoryLink" href="category/del-category" class="navLinks a_delete btn btn-sm md:btn-xs btn-error" title="<?php echo $this->translate->_("Click to delete selected category");?>"><?php echo $this->translate->_("Delete category");?></a>
              <a id="addCategoryItemLink" href="category/add-category-item" class="navLinks a_add btn btn-sm md:btn-xs" title="<?php echo $this->translate->_("Click to add new category item to this category");?>"><?php echo $this->translate->_("Add a category item");?></a>
              <a id="delCategoryItemLink" href="category/del-category-item" class="navLinks a_delete btn btn-sm md:btn-xs btn-error" title="<?php echo $this->translate->_("Click to remove this category item");?>"><?php echo $this->translate->_("Remove category item");?></a>
            </div>

          </div>

          <div class="grid gap-2 content-start">
            <div id="categorySelected" class=""></div>

          </div>

          <div id="categorySelectedForm" class="grid gap-2 content-start">
            <div id="CatNameDivContainer">
              <form id="catNameForm" enctype="application/x-www-form-urlencoded" action="" method="post">
                <dl class="zend_form">
                  <dt><label for="catItems" class="optional"><?php echo $this->translate->_("Category Name Translation");?>:</label></dt>
                  <dd>
                    <input type="text" value="" name="cat_name_lng" class="input input-sm w-full"/>
                    <input type="submit" value="<?php echo $this->translate->_("Save");?>" class="btn btn-sm md:btn-xs mt-2" />
                  </dd></dl>
                </form>
              </div>
              <a id="editcategoryItem" style="display:none"><?php echo $this->translate->_("Edit");?></a>
              <a id="deleteCategoryItem" class="a_delete" style="display:none" title="<?php echo $this->translate->_("Click to delete this category item");?>"><?php echo $this->translate->_("Delete this category item");?> </a>
              <div id="categoryItemForm"></div>
            </div>

          </div>

        </div>

        <!--Languages-->
        <div id="fragment-4">
          <div id="languageDiv" >
            <?php echo $this->languages;?>
          </div>
        </div>

        <!--Modules-->
        <div id="fragment-5">
          <div id="fragment-5wrapper" class="cssjswrapp2 bg-primary">

            <div id="modulesFormContainer" class="flex flex-col gap-2">
              <div class="w-8">
                <a id="fsbutton3" class="help fsbutton w-8" href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                    <path fill-rule="evenodd" d="M15 3.75a.75.75 0 0 1 .75-.75h4.5a.75.75 0 0 1 .75.75v4.5a.75.75 0 0 1-1.5 0V5.56l-3.97 3.97a.75.75 0 1 1-1.06-1.06l3.97-3.97h-2.69a.75.75 0 0 1-.75-.75Zm-12 0A.75.75 0 0 1 3.75 3h4.5a.75.75 0 0 1 0 1.5H5.56l3.97 3.97a.75.75 0 0 1-1.06 1.06L4.5 5.56v2.69a.75.75 0 0 1-1.5 0v-4.5Zm11.47 11.78a.75.75 0 1 1 1.06-1.06l3.97 3.97v-2.69a.75.75 0 0 1 1.5 0v4.5a.75.75 0 0 1-.75.75h-4.5a.75.75 0 0 1 0-1.5h2.69l-3.97-3.97Zm-4.94-1.06a.75.75 0 0 1 0 1.06L5.56 19.5h2.69a.75.75 0 0 1 0 1.5h-4.5a.75.75 0 0 1-.75-.75v-4.5a.75.75 0 0 1 1.5 0v2.69l3.97-3.97a.75.75 0 0 1 1.06 0Z" clip-rule="evenodd" />
                  </svg>
                </a>
              </div>

              <div id="modulesShow">
                <div style="display:none;"><?php echo $this->translate->_("Put in this object");?> <input id="putModulesInThis" class="checkbox-sm checkbox" type="checkbox" /></div>

                <?php echo $this->formChooseModules;?>
              </div>


              <div id="modulesSelected">
              </div>

            <!--<div id="modulesSelectedForm" style="width:250px;float:right;">
            <a id="editmodulesItem" style="display:none">Edit</a>
            <a id="deletemodulesItem" class="a_delete" style="display:none" title="<?php echo $this->translate->_("Click to delete this module item");?>">Delete this category item </a>
            <div id="modulesItemForm"></div>
          </div>
        -->
      </div>


      <div id="addModulesLinkDiv" >
        <!--<a id="installModulesLink" href="modules/install-module" class="navLinks a_add" title="<?php echo $this->translate->_("Click to install new module");?>">Install module</a>
        <a  id="delModulesLink" href="modules/del-module" class="navLinks a_delete" title="<?php echo $this->translate->_("Click to delete module");?>">Delete module</a>
        |-->
        <a id="editModulesLink" href="modules/edit-module/id/" class="navLinks help a_edit btn btn-sm md:btn-xs" title="<?php echo $this->translate->_("Click to edit this module settings");?>"><?php echo $this->translate->_("Edit module");?></a>
        <a id="enableModulesLink" href="modules/enable-all-modules" class="navLinks help a_add btn btn-sm md:btn-xs" title="<?php echo $this->translate->_("Click to enable all available modules.");?>"><?php echo $this->translate->_("Enable all modules");?></a>

      </div>

    </div>
  </div>

  <!--Images-->
  <div id="fragment-6">
    <div id="imagesContainer" class="grid gap-4">

      <!--Images on this site:-->
      <div id="imageFoldersShow" class="grid gap-2 content-start">
        <div>
          <?php echo $this->imagesFoldersForm;?>
        </div>
        <div id="addFolderLinkDiv" class="grid gap-2">
          <a id="addFolderLink" href="images/add-folder" class="navLinks a_add btn btn-sm md:btn-xs" title="<?php echo $this->translate->_("Click to create new folder for the images");?>"><?php echo $this->translate->_("Add a folder");?></a>
          <a id="delFolderLink" href="images/del-folder" class="navLinks a_delete btn btn-sm md:btn-xs btn-error" title="<?php echo $this->translate->_("Click to delete folder");?>"><?php echo $this->translate->_("Delete folder");?></a>
          <a id="addImageLink" href="images/add-image" class="navLinks a_add btn btn-sm md:btn-xs" title="<?php echo $this->translate->_("Click to add new image to this folder");?>"><?php echo $this->translate->_("Add images");?></a>
        </div>
      </div>
      <div id="imagesShow" class="grid gap-2 content-start">

      </div>

      <div class="grid gap-2 content-start">
        <a id="deleteImage" class="a_delete marginBottom5 btn btn-sm md:btn-xs btn-error" style="display:none" title="<?php echo $this->translate->_("Click to delete this image");?>"><?php echo $this->translate->_("Delete this image");?> </a>

        <a id="insertImage" class="a_add marginBottom5 btn btn-sm md:btn-xs" style="display:none" title="<?php echo $this->translate->_("Click to insert this image");?>"><?php echo $this->translate->_("Insert this image");?> </a>

        <a id="setBodyBgImage" class="a_add marginBottom5 btn btn-sm md:btn-xs" style="display:none" title="<?php echo $this->translate->_("Click to set background");?>"><?php echo $this->translate->_("Set background");?> </a>

        <div class="inline-flex gap-2 items-center">
          <?php echo $this->translate->_("Put image(s) in the selected object");?> <input id="putImagesInThis" class="checkbox-sm checkbox" type="checkbox" /> into the
          <!--<?php echo $this->translate->_("Single Image");?><input id="putSingleImageInThis" type="checkbox" />-->
        </div>

        <select id="bgSelect" class="help select select-sm md:select-xs w-full" title="<?php echo $this->translate->_("For this to work, set appropriate classes to the objects, lowercase (HEADER = header) except for the BODY, body is always there." );?>"><option>BODY</option><option>HEADER</option><option>SHEET</option><option>LEFTCOLUMN</option><option>RIGHTCOLUMN</option><option>FOOTER</option><option selected="selected">SELECTED-OBJECT</option></select>
        
        <div class="inline-flex gap-2 items-center">
          <input type="checkbox" class="checkbox-sm checkbox" name="NR" value="repeat" id="NR" /> no-repeat
          <input type="checkbox" class="checkbox-sm checkbox" name="fixedBg" value="fixed"  id="fixedBg" /> Fixed
        </div>

        <!--Image path:-->
        <div id="imagePathShow"></div>
        <div id="imageDetails"></div>
      </div>
    </div>
  </div>


  <!--CSS-->
  <div id="fragment-7">
    <div id="fragment-7wrapper" class="cssjswrapp bg-primary">
      <div class="grid gap-2">
        <div class="w-8">
          <a href="#" class="help fsbutton w-8" id="fsbutton" >
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
              <path fill-rule="evenodd" d="M15 3.75a.75.75 0 0 1 .75-.75h4.5a.75.75 0 0 1 .75.75v4.5a.75.75 0 0 1-1.5 0V5.56l-3.97 3.97a.75.75 0 1 1-1.06-1.06l3.97-3.97h-2.69a.75.75 0 0 1-.75-.75Zm-12 0A.75.75 0 0 1 3.75 3h4.5a.75.75 0 0 1 0 1.5H5.56l3.97 3.97a.75.75 0 0 1-1.06 1.06L4.5 5.56v2.69a.75.75 0 0 1-1.5 0v-4.5Zm11.47 11.78a.75.75 0 1 1 1.06-1.06l3.97 3.97v-2.69a.75.75 0 0 1 1.5 0v4.5a.75.75 0 0 1-.75.75h-4.5a.75.75 0 0 1 0-1.5h2.69l-3.97-3.97Zm-4.94-1.06a.75.75 0 0 1 0 1.06L5.56 19.5h2.69a.75.75 0 0 1 0 1.5h-4.5a.75.75 0 0 1-.75-.75v-4.5a.75.75 0 0 1 1.5 0v2.69l3.97-3.97a.75.75 0 0 1 1.06 0Z" clip-rule="evenodd" />
            </svg>
          </a>
        </div>
        <div>
          <div><?php echo $this->translate->_("Choose Object");?>:</div>
          <select id="objListForCss" class="select select-sm w-full" size="1"></select>
        <!--<?php echo $this->translate->_("Choose class");?>:
          <select id="eventListForCss" size="1"></select>-->
          <a id="addCssCodeA" class="navLinks a_add noAjaxEvent btn btn-sm md:btn-xs mt-2"><?php echo $this->translate->_("Add Code");?></a>

        </div>
        <div class="grid">
          <textarea id="pageCSS" name="pageCSS" class="hidden codepress css min-h-96">
            <?php echo $this->css;?>
          </textarea>
          <div id="pageCSS-ace" class="w-full h-full min-h-96"><?php echo $this->css;?></div>
          <a id="saveCssCodeA" class="navLinks a_save btn btn-sm mt-4 btn-sm md:btn-xs md:mt-2"><?php echo $this->translate->_("Save This Code");?></a>
        </div>
      </div>
      </div>

    </div>

    <!--JS-->
    <div id="fragment-8">
      <div id="fragment-8wrapper" class="cssjswrapp bg-primary">
        <div class="w-8">
          <a href="#" class="help fsbutton w-8" id="fsbutton2" >
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
              <path fill-rule="evenodd" d="M15 3.75a.75.75 0 0 1 .75-.75h4.5a.75.75 0 0 1 .75.75v4.5a.75.75 0 0 1-1.5 0V5.56l-3.97 3.97a.75.75 0 1 1-1.06-1.06l3.97-3.97h-2.69a.75.75 0 0 1-.75-.75Zm-12 0A.75.75 0 0 1 3.75 3h4.5a.75.75 0 0 1 0 1.5H5.56l3.97 3.97a.75.75 0 0 1-1.06 1.06L4.5 5.56v2.69a.75.75 0 0 1-1.5 0v-4.5Zm11.47 11.78a.75.75 0 1 1 1.06-1.06l3.97 3.97v-2.69a.75.75 0 0 1 1.5 0v4.5a.75.75 0 0 1-.75.75h-4.5a.75.75 0 0 1 0-1.5h2.69l-3.97-3.97Zm-4.94-1.06a.75.75 0 0 1 0 1.06L5.56 19.5h2.69a.75.75 0 0 1 0 1.5h-4.5a.75.75 0 0 1-.75-.75v-4.5a.75.75 0 0 1 1.5 0v2.69l3.97-3.97a.75.75 0 0 1 1.06 0Z" clip-rule="evenodd" />
            </svg>
          </a>
        </div>
        <div>
          <div>
            <div><?php echo $this->translate->_("Choose Object");?>:</div>
            <select id="objListForJs" class="select select-sm md:select-xs w-full" size="1"></select>
          </div>
          <div class="grid gap-2">
            <div><?php echo $this->translate->_("Choose event");?>:</div>
            <select id="eventListForJs" class="select select-sm md:select-xs w-full" size="1">
              <option>click</option>
              <option>dblclick</option>
              <option>mouseover</option>
              <option>mouseout</option>
            </select>
          </div>
          <a id="addJsCodeA" class="navLinks a_add noAjaxEvent btn btn-sm md:btn-xs mt-2 mb-4"><?php echo $this->translate->_("Add Code");?></a>
        </div>

        <div class="grid gap-2">
          <textarea id="pageJS" name="pageJS" class="hidden codepress javascript min-h-96">
            <?php echo $this->js;?>
          </textarea>
          <div id="pageJS-ace" class="w-full min-h-96"><?php echo $this->js;?></div>
          <a id="saveJsCodeA" class="navLinks a_save btn btn-sm md:btn-xs "><?php echo $this->translate->_("Save This Code");?></a>
        </div>

      </div>
    </div>


    <!--Settings-->
    <div id="fragment-9">
      <?php echo $this->settings;?>
    </div>

  </div>

</div>

</div>

</div>

<script type="text/javascript" >
<?php include('creator.js');?>
</script>
<script type="text/javascript" >
<?php //include('creator2.js');?>
</script>
<!--<script type="text/javascript" src="<?php echo $this->host;?>js/creatorObf.js"></script>-->
<script type="text/javascript">
absoluteUrl = '<?php echo $this->host;?>';
</script>
