<?php
/**
 * CMS-IDE Visual CMS
 *
 * @category   Layouts
 * @package    CMS-IDE
 *  Copyright (C) 2010-2021  Nebojsa Tomic
 *  
 *  This file is part of CMS-IDE.
 *     
 *  CMS-IDE is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 3 of the License, or (at your option) any later version.
 *
 *  CMS-IDE is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * 
 * 
 */
 ?>
 <div class="grid grid-cols-2 gap-2 items-center">
 	Left: <input id="shdwLeft" class="input input-sm" size="1" value="4" type="text">
 	Top: <input  id="shdwTop" class="input input-sm" size="1" value="4" type="text">
 	Blur: <input id="shdwBlur" class="input input-sm" size="1" value="2" type="text">
 	Opacity: <input id="shdwOpacity" class="input input-sm" size="2" value="0.5" type="text">
 	Color: <input id="shdwColor" class="input input-sm" size="6" value="black" type="text">

 	<input  id="shadowParamButton" class="btn btn-xs btn-secondary col-span-2" value="Apply" type="button">
 </div>