<?php
/**
* IDE21 Content Management System
*
* @category   Layouts
* @package    IDE21
*  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
*
*  This file is part of IDE21.
*
*  IDE21 is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
*
*
*
*/
?>
<?php
echo $this->output;
?>

<!--<script type="text/javascript" src="<?php echo $this->host;?>js/view.js"></script><script type="text/javascript" src="<?php echo $this->host;?>js/frontend.js"></script><script type="text/javascript" src="<?php echo $this->host;?>js/default.js"></script>--><!--js not compressed-->
<!--<script type="text/javascript" src="<?php echo $this->host;?>js/view.min.js"></script><script type="text/javascript" src="<?php echo $this->host;?>js/frontend.min.js"></script><script type="text/javascript" src="<?php echo $this->host;?>js/default.min.js"></script>-->
