<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
<?php
echo $this->form;
?>
<script type="text/javascript">
        $('#addRowForm').ajaxForm(function(data){
            $('#dialogDiv').remove();
            
            jsin = eval("(" + data + ")" );
            rowid = jsin["out"]["row"] ;
            rowData = jsin["out"]["rowData"];            
            tid = jsin["out"]["tableid"] ;
            
            $("#uta_" + tid ).append('<tr id="' + rowid + '"><td>' + rowid + '</td>' + rowData + '<td><a value="'+ tid +'" id="edit_'+ rowid + '" class="navLinks uniTableAdmin a_edit" href="" ></a>&nbsp;<a href="" id="'+ rowid + '" class="navLinks uniTableAdmin a_delete" value="' + tid + '"></a></td></tr>').fadeIn(1000);
            
            $('#ajaxEventMask').click();//removing the mask            
        });
</script>        