<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
<?php
echo $this->form;
?>
<script type="text/javascript">

        
        $('#editRowForm').ajaxForm(function(data){
            $('#dialogDiv').remove();//removing the dialog  
                      
            //alert(data);
            //json variables
            jsin = eval("(" + data + ")" );
            rowid = jsin["out"]["row"] ;
            rowData = jsin["out"]["rowData"];            
            tid = jsin["out"]["tableid"] ;
                        
            //alert( rowid + "_" + tid);
            //updating table
            $("#uta_" + tid + " tr[id^='" + rowid + "']").fadeOut(2000);
            $("#uta_" + tid + " tr[id^='" + rowid + "']").html('<td>' + rowid + '</td>' + rowData + '<td><a value="'+ tid +'" id="edit_'+ rowid + '" class="navLinks uniTableAdmin a_edit" href="" ></a>&nbsp;<a href="" id="'+ rowid + '" class="navLinks uniTableAdmin a_delete" value="' + tid + '"></a></td>');
            $("#uta_" + tid + " tr[id^='" + rowid + "']").fadeIn(1000);
            ajaxEmitMessage(lang.Done);                  
            setTimeout("$('#ajaxEventMask').click()", 1000);
        }, "json");
</script>    
   