<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
<?php

//print_r($this->cols );
foreach ($this->cols as $col ) {
$colone[] = $col['Field'];
}

$xml = <<<XML
<rows>
<page>1</page>
<total>2</total>
<records>13</records>
XML;

foreach ($this->data as $data) {


    $xml .= '<row id="' .$data[$colone[0]] . '"><select><option>';
    // foreach column
    //$i = 1;
    foreach ($colone as $kolona) {
    $xml .= '<cell>' . $data[$kolona] . '</cell>';
    //$i++;
    //$xml .= '<cell>' . $data['name'] . '</cell>';
    //$xml .= '<cell>' . $data['message'] . '</cell>';
    //$xml .= '<cell>' . $data['contact'] . '</cell>';
   } 
    
    $xml .= '</option></select></row>';
}

$xml .= "</rows>" ;   


echo $xml;
//print_r($colone );