<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *
 *  This file is part of IDE21.
 *
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 *
 *
 */
 ?>
<?php
$pid = $this->pid;

if ($pid == ""){
    $xmlFile = "config.xml";
} else {
    $xmlFile = "config_" . $pid . ".xml";
}
?>
<!--
<script type="text/javascript">
		var flashvars = {};
		flashvars.xml = absoluteUrl + "js/cu3er/<?php echo $xmlFile;?>";
		//flashvars.font = "font.swf";
		var attributes = {};
		attributes.wmode = "transparent";
		attributes.id = "slider";
		swfobject.embedSWF(absoluteUrl + "js/cu3er/cu3er.swf", "cu3er-container", "850", "245", "9", absoluteUrl + "js/cu3er/expressInstall.swf", flashvars, attributes);
</script>


<div id="cu3er-container" style="width:850px;height:255px;">
    <a href="http://www.adobe.com/go/getflashplayer">
        <img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player" />
    </a>
</div>
-->
