<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 */
?>
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="generator" content="NeT">
  <title> This site is Under Construction</title>
  <link rel="shortcut icon" type="image/x-icon" href="/images/ide21logo.svg">
  <style type="text/css">
  body {padding:0; margin: 0; width: 100vw; height: 100vh;background: #d3d3d3;}
  </style>
</head>
<body>
    <div style="position:absolute;top:0;left:0;width:100%;height:95%;z-index:9;background:#d3d3d3;">
        <img src="/images/ide21logo.svg" height="100%" style="width: 100%;object-fit: contain;">
    </div>
</body>
</html>