<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
 <div class="divider"></div>
 <div class="bg-secondary p-4 mt-4 mb-4 font-bold rounded text-primary-content">
<?php echo $this->translate->_("Available Forms");?>:
</div>
<?php
echo $this->formsList;
?>
<div class="divider"></div>
<div class="bg-secondary p-4 mt-4 mb-4 font-bold rounded text-primary-content">
<?php echo $this->translate->_("Form Fields");?>:
</div>
<?php
echo $this->formsFieldsList;
?>
<div class="divider"></div>
<div class="bg-secondary p-4 mt-4 mb-4 font-bold rounded text-primary-content">
<?php echo $this->translate->_("Contacts");?>:
</div>
<?php
echo $this->contactsList;
?>
