<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
<script type="text/javascript" >
$('#adminAddUserForm').ajaxForm(function(data){
    //jsin = eval("(" + data + ")" );
    //allWell = jsin["out"]["allWell"] ;
    //form = jsin["out"]["form"] ;
    //message = jsin["out"]["message"] ;
    allWell = "<?php echo $this->allWell;?>";

                
    if (allWell  == "1") {
        $('#dialogDiv').remove();
        $('#moduleName').change();
        ajaxEmitMessage(message);
        setTimeout("clickMask()", 1000); //closing all 
    } else {
        //clickMask();
        $('#ajaxEventMessage').remove();
        $('#dialogDiv').html('<div id="closeDialogDiv"></div>' + data);
        $('#moduleName').change();
        //ajaxEmitMessage(data);
        //setTimeout("clickMask()", 1000); //closing all     
    } 
                            
});
</script>