<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
<div class="bg-secondary text-secondary-content p-4 mt-4 mb-4 font-bold rounded">
<?php echo $this->translate->_("Users");?>:
</div>
<?php
echo $this->usersList;
?>
<div class="divider"></div>
 <div class="bg-secondary text-secondary-content p-4 mt-4 mb-4 font-bold rounded">
<?php echo $this->translate->_("Roles");?>:
</div>
<?php
echo $this->rolesList;
?>
<div class="divider"></div>