<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
<?php
echo $this->output;
?>
<script type="text/javascript">
$('body').livequery(function(){
        bodyBg = "<?php echo  $this->bg ; ?>";
        //alert(bodyBg);
        bodyBgA = bodyBg.split(";");
        bodyBgSize = bodyBgA[1] + ";" + bodyBgA[2] + ";" + bodyBgA[3] + ";" +bodyBgA[4] + ";";
        if(bodyBgA[1]){
                bodyBgSizeA = new Array;
                bodyBgSizeA[0] = bodyBgA[1].replace(":100%", "");
                bodyBgSizeA[1] = bodyBgA[1].replace("-moz-background-size:", "");
        
                bodyBgSizeA[2] = bodyBgA[2].replace(":100%", "");
                bodyBgSizeA[3] = bodyBgA[2].replace("-webkit-background-size:", "");
        
                bodyBgSizeA[4] = bodyBgA[3].replace(":100%", "");
                bodyBgSizeA[5] = bodyBgA[3].replace("-o-background-size:", "");
        
                bodyBgSizeA[6] = bodyBgA[4].replace(":100%", "");
                bodyBgSizeA[7] = bodyBgA[4].replace("background-size:", "");
        
        }        

    //$(this).css({background:"<?php echo str_replace(';', '', $this->bg);?>"});
        //alert("<?php echo  $this->bg ; ?>");
        //$('body').css({background:"<?php echo  $this->bg ; ?>"});
});    
</script>
