<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
?>
<?php
echo $this->form;
?>
<script type="text/javascript">
  $('#addMenuItemSubmit').one('click', function (evt) {

    $(this).closest('form').ajaxForm(function(data){

      $('#dialogDiv').remove();
      $('#menuName').change();

      ajaxEmitMessage(data);
      setTimeout("clickMask()", 2000); //closing all
      evt.preventDefault();
      return false;
    });

  });
</script>
