<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
<?php
echo $this->form;
?>
<script type="text/javascript">
$('#addMenuItemSubmit').one('click', function (evt) {
    /* prevent default action */
    evt.preventDefault();
    /* code to be executed once */
    /**
     * disable default action (this handler will be attached after first 
     * submit event and it will prevent any further submit action
     */
     $(this).closest('form').ajaxForm(function(data){
        //submiting addmenu item form

            $('#dialogDiv').remove();
            $('#menuName').change();
            
            ajaxEmitMessage(data);
            setTimeout("clickMask()", 1000); //closing all          
        evt.preventDefault();
        return false;
        
     });

});
</script>
<script type="text/javascript">
/*        //submiting addmenu item form
        $('#addMenuItemForm').ajaxForm(function(data){
            $('#dialogDiv').remove();
            $('#menuName').change();
            
            ajaxEmitMessage(data);
            setTimeout("clickMask()", 1000); //closing all 
        });  
        */
</script>