<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *
 *
 *
 *
 *
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 *
 *
 *
 *
 *
 * 
 * 
 */
 ?>
<?php echo $this->formAddMenu;
?>
<script type="text/javascript">

$('#addMenuForm').ajaxForm(function(data){
    
    mn = $('#newMenuName').attr("value");
    $('#dialogDiv').remove();

    jsin = eval("(" + data + ")" );
    menuItemId = jsin["out"]["menuItemId"] ;
    menuMessage = jsin["out"]["message"] ;
    
    //TREBA DODATI VALUE DA BI SE UPDATOVAO ID UNESENOG MENIJA
    //alert(data + " *<?php echo $this->menuName;?>"); 
    $('#menuName').append('<option value="' + menuItemId + '">' +  mn + "</option>");
    $('#menuNameAssign').append('<option value="' + menuItemId + '">' +  mn + "</option>");
    
    //messages in ajaxevent
    ajaxEmitMessage(menuMessage);
    setTimeout("clickMask()", 1000); //closing all  

    
}, "json");
</script>