<?php
/**
 * IDE21 Content Management System
 *
 * @category   Layouts
 * @package    IDE21
 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)
 *  
 *  This file is part of IDE21.
 *     
 *  IDE21 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * 
 * 
 */
 ?>
<div class="flex gap-2">
Weight:
<a href="" class="a_weightUp navLinks help" title="Bring this menu item up">
    <svg class="w-6 h-6 fill-current bg-primary text-white rounded-full" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" >
      <path fill-rule="evenodd" d="M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25Zm.53 5.47a.75.75 0 0 0-1.06 0l-3 3a.75.75 0 1 0 1.06 1.06l1.72-1.72v5.69a.75.75 0 0 0 1.5 0v-5.69l1.72 1.72a.75.75 0 1 0 1.06-1.06l-3-3Z" clip-rule="evenodd" />
    </svg>
</a>

<a href="" class="a_weightDw navLinks help" title="Bring this menu item down" >
    <svg class="w-6 h-6 fill-current bg-primary text-white rounded-full" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
      <path fill-rule="evenodd" d="M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25Zm-.53 14.03a.75.75 0 0 0 1.06 0l3-3a.75.75 0 1 0-1.06-1.06l-1.72 1.72V8.25a.75.75 0 0 0-1.5 0v5.69l-1.72-1.72a.75.75 0 0 0-1.06 1.06l3 3Z" clip-rule="evenodd" />
    </svg>
</a>

</div>

<?php echo $this->menuItemForm;

?>

<script type="text/javascript">

$('.a_weightUp').click(function(){

    ajaxEventDone("Changing the weight...");

    $.post(absoluteUrl + "menu/change-weight/to/up/itid/" + $('#menuItemForm').attr("value"), function(data){

        ajaxEmitMessage(data);

        setTimeout("clickMask()", 1000);  

        dontChangeMenuItemForm = 1;        

        $('#chooseMenuForm').change();



        //alert(data);

    });

});



$('.a_weightDw').click(function(){

    ajaxEventDone("Changing the weight...");

    $.post(absoluteUrl + "menu/change-weight/to/down/itid/" + $('#menuItemForm').attr("value"), function(data){

        ajaxEmitMessage(data);

        setTimeout("clickMask()", 1000);  

        dontChangeMenuItemForm = 1;        

        $('#chooseMenuForm').change();



        //alert(data);

    });

});



$('#editMenuItemForm').ajaxForm(function(data){

    //alert(data);

    ajaxEmitMessage(data);

    setTimeout("clickMask()", 1000);       

    $('#chooseMenuForm').change();

})

</script>