<?php

/**

 * IDE21 Content Management System

 *

 * @category   Layouts

 * @package    IDE21

 *  Copyright (C) 2010-present  Nebojsa Tomic (nebojsatmc@gmail.com)

 *  

 *  This file is part of IDE21.

 *     

 *

 *

 *

 *

 *

 *  IDE21 is distributed in the hope that it will be useful,

 *  but WITHOUT ANY WARRANTY; without even the implied warranty of

 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 *

 *

 *

 *

 *

 *

 * 

 * 

 */

 ?>
<?php echo $this->menuItems;
?>
<script type="text/javascript">
$('#addMenuItemSubmit2').one('click', function (evt) {
    /* prevent default action */
    evt.preventDefault();
    /* code to be executed once */
    /**
     * disable default action (this handler will be attached after first 
     * submit event and it will prevent any further submit action
     */
     $(this).closest('form').ajaxForm(function(data){
        ajaxEventDone(data);                 
        ajaxEmitMessage(data);
        setTimeout("clickMask()", 2000);
        $('#dialogDiv').remove();
        $('#menuNameAssign').prop("value", "select");          
        evt.preventDefault();
        return false;
        
     });

});
</script>