<?php
/**
 * CMS-IDE Visual CMS
 *
 * @category   Layouts
 * @package    CMS-IDE
 *  Copyright (C) 2010-2021  Nebojsa Tomic
 *  
 *  This file is part of CMS-IDE.
 *     
 *  CMS-IDE is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 3 of the License, or (at your option) any later version.
 *
 *  CMS-IDE is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * 
 * 
 */
 ?>
<?php
setlocale(LC_TIME, "fr_FR");
//echo $this->translate->_("Created by: ") . $this->pageinfo['fullname'] . $this->translate->_(", ") . date("d.m.Y, G:H:s", $this->pageinfo['created'] );
echo '<div id="pageinfoDiv" class="blackTheme">' . $this->translate->_("Created by: ") . $this->pageinfo['fullname'] . $this->translate->_(", ") . strftime("%A %d.%B %Y %H:%M",  $this->pageinfo['created'] ) . '</div>';